<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="2.8 Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues | Intermediate Statistics with R" />
<meta property="og:type" content="book" />


<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="2.8 Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues | Intermediate Statistics with R">

<title>2.8 Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues | Intermediate Statistics with R</title>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if bootstrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover" id="toc-cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments" id="toc-acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1" id="toc-chapter1"><span class="toc-section-number">1</span> Preface</a>
<ul>
<li><a href="1.1-section1-1.html#section1-1" id="toc-section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1.2-section1-2.html#section1-2" id="toc-section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1.3-section1-3.html#section1-3" id="toc-section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1.4-section1-4.html#section1-4" id="toc-section1-4"><span class="toc-section-number">1.4</span> R Markdown</a></li>
<li><a href="1.5-section1-5.html#section1-5" id="toc-section1-5"><span class="toc-section-number">1.5</span> Grammar of Graphics</a></li>
<li><a href="1.6-section1-6.html#section1-6" id="toc-section1-6"><span class="toc-section-number">1.6</span> Exiting RStudio</a></li>
<li><a href="1.7-section1-7.html#section1-7" id="toc-section1-7"><span class="toc-section-number">1.7</span> Chapter summary</a></li>
<li><a href="1.8-section1-8.html#section1-8" id="toc-section1-8"><span class="toc-section-number">1.8</span> Summary of important R code</a></li>
<li><a href="1.9-section1-9.html#section1-9" id="toc-section1-9"><span class="toc-section-number">1.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2" id="toc-chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a>
<ul>
<li><a href="2.1-section2-1.html#section2-1" id="toc-section2-1"><span class="toc-section-number">2.1</span> Data wrangling and density curves</a></li>
<li><a href="2.2-section2-2.html#section2-2" id="toc-section2-2"><span class="toc-section-number">2.2</span> Pirate-plots</a></li>
<li><a href="2.3-section2-3.html#section2-3" id="toc-section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2.4-section2-4.html#section2-4" id="toc-section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2.5-section2-5.html#section2-5" id="toc-section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2.6-section2-6.html#section2-6" id="toc-section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2.7-section2-7.html#section2-7" id="toc-section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2.8-section2-8.html#section2-8" id="toc-section2-8"><span class="toc-section-number">2.8</span> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</a></li>
<li><a href="2.9-section2-9.html#section2-9" id="toc-section2-9"><span class="toc-section-number">2.9</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2.10-section2-10.html#section2-10" id="toc-section2-10"><span class="toc-section-number">2.10</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2.11-section2-11.html#section2-11" id="toc-section2-11"><span class="toc-section-number">2.11</span> Chapter summary</a></li>
<li><a href="2.12-section2-12.html#section2-12" id="toc-section2-12"><span class="toc-section-number">2.12</span> Summary of important R code</a></li>
<li><a href="2.13-section2-13.html#section2-13" id="toc-section2-13"><span class="toc-section-number">2.13</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3" id="toc-chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a>
<ul>
<li><a href="3.1-section3-1.html#section3-1" id="toc-section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3.2-section3-2.html#section3-2" id="toc-section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell means and reference-coding)</a></li>
<li><a href="3.3-section3-3.html#section3-3" id="toc-section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3.4-section3-4.html#section3-4" id="toc-section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3.5-section3-5.html#section3-5" id="toc-section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3.6-section3-6.html#section3-6" id="toc-section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3.7-section3-7.html#section3-7" id="toc-section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for the Overtake data</a></li>
<li><a href="3.8-section3-8.html#section3-8" id="toc-section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3.9-section3-9.html#section3-9" id="toc-section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3.10-section3-10.html#section3-10" id="toc-section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4" id="toc-chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a>
<ul>
<li><a href="4.1-section4-1.html#section4-1" id="toc-section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4.2-section4-2.html#section4-2" id="toc-section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4.3-section4-3.html#section4-3" id="toc-section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4.4-section4-4.html#section4-4" id="toc-section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4.5-section4-5.html#section4-5" id="toc-section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4.6-section4-6.html#section4-6" id="toc-section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs and Estimability</a></li>
<li><a href="4.7-section4-7.html#section4-7" id="toc-section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4.8-section4-8.html#section4-8" id="toc-section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4.9-section4-9.html#section4-9" id="toc-section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5" id="toc-chapter5"><span class="toc-section-number">5</span> Chi-square tests</a>
<ul>
<li><a href="5.1-section5-1.html#section5-1" id="toc-section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and tableplots</a></li>
<li><a href="5.2-section5-2.html#section5-2" id="toc-section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5.3-section5-3.html#section5-3" id="toc-section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5.4-section5-4.html#section5-4" id="toc-section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5.5-section5-5.html#section5-5" id="toc-section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.6-section5-6.html#section5-6" id="toc-section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.7-section5-7.html#section5-7" id="toc-section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5.8-section5-8.html#section5-8" id="toc-section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5.9-section5-9.html#section5-9" id="toc-section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5.10-section5-10.html#section5-10" id="toc-section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5.11-section5-11.html#section5-11" id="toc-section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5.12-section5-12.html#section5-12" id="toc-section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5.13-section5-13.html#section5-13" id="toc-section5-13"><span class="toc-section-number">5.13</span> Summary of important R code</a></li>
<li><a href="5.14-section5-14.html#section5-14" id="toc-section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6" id="toc-chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a>
<ul>
<li><a href="6.1-section6-1.html#section6-1" id="toc-section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6.2-section6-2.html#section6-2" id="toc-section6-2"><span class="toc-section-number">6.2</span> Estimating the correlation coefficient</a></li>
<li><a href="6.3-section6-3.html#section6-3" id="toc-section6-3"><span class="toc-section-number">6.3</span> Relationships between variables by groups</a></li>
<li><a href="6.4-section6-4.html#section6-4" id="toc-section6-4"><span class="toc-section-number">6.4</span> Inference for the correlation coefficient</a></li>
<li><a href="6.5-section6-5.html#section6-5" id="toc-section6-5"><span class="toc-section-number">6.5</span> Are tree diameters related to tree heights?</a></li>
<li><a href="6.6-section6-6.html#section6-6" id="toc-section6-6"><span class="toc-section-number">6.6</span> Describing relationships with a regression model</a></li>
<li><a href="6.7-section6-7.html#section6-7" id="toc-section6-7"><span class="toc-section-number">6.7</span> Least Squares Estimation</a></li>
<li><a href="6.8-section6-8.html#section6-8" id="toc-section6-8"><span class="toc-section-number">6.8</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6.9-section6-9.html#section6-9" id="toc-section6-9"><span class="toc-section-number">6.9</span> Outliers: leverage and influence</a></li>
<li><a href="6.10-section6-10.html#section6-10" id="toc-section6-10"><span class="toc-section-number">6.10</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6.11-section6-11.html#section6-11" id="toc-section6-11"><span class="toc-section-number">6.11</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6.12-section6-12.html#section6-12" id="toc-section6-12"><span class="toc-section-number">6.12</span> Chapter summary</a></li>
<li><a href="6.13-section6-13.html#section6-13" id="toc-section6-13"><span class="toc-section-number">6.13</span> Summary of important R code</a></li>
<li><a href="6.14-section6-14.html#section6-14" id="toc-section6-14"><span class="toc-section-number">6.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7" id="toc-chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a>
<ul>
<li><a href="7.1-section7-1.html#section7-1" id="toc-section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7.2-section7-2.html#section7-2" id="toc-section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7.3-section7-3.html#section7-3" id="toc-section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7.4-section7-4.html#section7-4" id="toc-section7-4"><span class="toc-section-number">7.4</span> Randomization-based inferences for the slope coefficient</a></li>
<li><a href="7.5-section7-5.html#section7-5" id="toc-section7-5"><span class="toc-section-number">7.5</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7.6-section7-6.html#section7-6" id="toc-section7-6"><span class="toc-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7.7-section7-7.html#section7-7" id="toc-section7-7"><span class="toc-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7.8-section7-8.html#section7-8" id="toc-section7-8"><span class="toc-section-number">7.8</span> Chapter summary</a></li>
<li><a href="7.9-section7-9.html#section7-9" id="toc-section7-9"><span class="toc-section-number">7.9</span> Summary of important R code</a></li>
<li><a href="7.10-section7-10.html#section7-10" id="toc-section7-10"><span class="toc-section-number">7.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8" id="toc-chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a>
<ul>
<li><a href="8.1-section8-1.html#section8-1" id="toc-section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8.2-section8-2.html#section8-2" id="toc-section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8.3-section8-3.html#section8-3" id="toc-section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8.4-section8-4.html#section8-4" id="toc-section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8.5-section8-5.html#section8-5" id="toc-section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8.6-section8-6.html#section8-6" id="toc-section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8.7-section8-7.html#section8-7" id="toc-section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8.8-section8-8.html#section8-8" id="toc-section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8.9-section8-9.html#section8-9" id="toc-section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8.10-section8-10.html#section8-10" id="toc-section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8.11-section8-11.html#section8-11" id="toc-section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8.12-section8-12.html#section8-12" id="toc-section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8.13-section8-13.html#section8-13" id="toc-section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8.14-section8-14.html#section8-14" id="toc-section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8.15-section8-15.html#section8-15" id="toc-section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8.16-section8-16.html#section8-16" id="toc-section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8.17-section8-17.html#section8-17" id="toc-section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9" id="toc-chapter9"><span class="toc-section-number">9</span> Case studies</a>
<ul>
<li><a href="9.1-section9-1.html#section9-1" id="toc-section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9.2-section9-2.html#section9-2" id="toc-section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9.3-section9-3.html#section9-3" id="toc-section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9.4-section9-4.html#section9-4" id="toc-section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9.5-section9-5.html#section9-5" id="toc-section9-5"><span class="toc-section-number">9.5</span> What do didgeridoos really do about sleepiness?</a></li>
<li><a href="9.6-section9-6.html#section9-6" id="toc-section9-6"><span class="toc-section-number">9.6</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references" id="toc-references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section2-8" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</h2>
<!-- \sectionmark{Reproducibility Crisis} -->
<p>In the previous examples, some variation in p-values was observed as different methods (parametric, nonparametric) were applied to the same data set and in the permutation approach, the p-values can vary as well from one set of permutations to another. P-values also vary based on randomness in the data that were collected – take a different (random) sample and you will get different data and a different p-value. We want the best estimate of a p-value we can obtain, so should use the best sampling method and inference technique that we can. But it is just an estimate of the evidence against the null hypothesis. These sources of variability make fixed <span class="math inline">\(\alpha\)</span> NHST especially worry-some as sampling variability could take a p-value from just below to just above <span class="math inline">\(\alpha\)</span> and this would lead to completely different inferences if the only focus is on rejecting the null hypothesis at a fixed significance level. But viewing p-values on a gradient from extremely strong (close to 0) to no (1) evidence against the null hypothesis, p-values of, say, 0.046 and 0.054 provide basically the same evidence against the null hypothesis. The fixed <span class="math inline">\(\alpha\)</span> decision-making is tied into the use of the terminology of “significant results” or, slightly better, “statistically significant results” that are intended to convey that there was sufficient evidence to reject the null hypothesis at some pre-decided <span class="math inline">\(\alpha\)</span> level. You will notice that this is the only time that the “s-word” (significant) is considered here.</p>
<p></p>
<p>The focus on p-values has been criticized for a suite of reasons <span class="citation">(<a href="#ref-Wasserstein2016">Wasserstein and Lazar 2016</a>)</span>. There are situations when p-values do not address the question of interest or the fact that a small p-value was obtained is so un-surprising that one wonders why it was even reported. For example, in Smith <span class="citation">(<a href="#ref-Smith2014">Smith 2014</a>)</span> the researcher considered bee sting pain ratings across 27 different body locations<a href="#fn48" class="footnote-ref" id="fnref48"><sup>48</sup></a>. I don’t think anyone would be surprised to learn that there was strong evidence against the null hypothesis of no difference in the true mean pain ratings across different body locations. What is really of interest are the differences in the means – especially which locations are most painful and how much more painful those locations were than others, on average.</p>
<p>As a field, Statistics is trying to encourage a move away from the focus on p-values and the use of the term “significant”, even when modified by “statistically”. There are a variety of reasons for this change. Science (especially in research going into academic journals and in some introductory statistics books) has taken to using p-value &lt; 0.05 and rejected null hypotheses as the only way to “certify” that a result is interesting. It has (and unfortunately still is) hard to publish a paper with a primary result with a p-value that is higher than 0.05, even if the p-value is close to that “magical” threshold. One thing that is lost when using that strict cut-off for decisions is that any p-value that is not exactly 1 suggests that there is at least some evidence against the null hypothesis in the data and that evidence is then on a continuum from none to very strong. And that p-values are both a function of the size of the difference and the sample size. It is easy to get small p-values for small size differences with large data sets. A small p-value can be associated with an unimportant (not practically meaningful) size difference. And large p-values, especially in smaller sample situations, could be associated with very meaningful differences in size even though evidence is not strong against the null hypothesis. It is critical to always try to estimate and discuss the size of the differences, whether a large or small p-value is encountered.</p>
<p>There are some other related issues to consider in working with p-values that help to illustrate some of the issues with how p-values and “statistical significance” are used in practice. In many studies, researchers have a suite of outcome variables that they measure on their subjects. For example, in an agricultural experiment they might measure the yield of the crops, the protein concentration, the digestibility, and other characteristics of the crops. In various “omics” fields such as genomics, proteomics, and metabolomics, responses for each subject on hundreds, thousands, or even millions of variables are considered and a p-value may be generated for each of those variables. In education, researchers might be interested in impacts on grades (as in the previous discussion) but we could also be interested in reading comprehension, student interest in the subject, and the amount of time spent studying, each as response variables in their own right. In each of these situations it means that we are considering not just one null hypothesis and assessing evidence against it, but are doing it many times, from just a few to millions of repetitions. There are two aspects of this process and implications for research to explore further: the impacts on scientific research of focusing solely on “statistically significant” results and the impacts of considering more than one hypothesis test in the same study.</p>
<p>There is the systematic bias in scientific research that has emerged from scientists having a difficult time publishing research if p-values for their data are not smaller than 0.05. This has two implications. Many researchers have assumed that results with “large” p-values are not interesting – so they either exclude these results from papers (they put them in <em>their</em> file drawer instead of into their papers – the so-called “file-drawer” bias) or reviewers reject papers because they did not have small p-values to support their discussions (only results with small p-values are judged as being of interest for publication – the so-called “publication bias”). Some also include bias from researchers only choosing to move forward with attempting to publish results if they are in the same direction that the researchers expect/theorized as part of this problem – ignoring results that contradict their theories is an example of “confirmation bias” but also would hinder the evolution of scientific theories to ignore contradictory results. But since most researchers focus on p-values and not on estimates of size (and direction) of differences, that will be our focus here.</p>
<p>We will use some of our new abilities in R to begin to study some of the impacts of systematically favoring only results with small p-values using a “simulation study” inspired by the explorations in <span class="citation">Schneck (<a href="#ref-Schneck2017">2017</a>)</span>. Specifically, let’s focus on the bicycle passing data. We start with assuming that there really is no difference in the two groups, so the true mean is the same in both groups, the variability is the same around the means in the two groups, and all responses follow normal distributions. This is basically like the permutation idea where we assumed the group labels could be equivalently swapped among responses if the null hypothesis were true except that observations will be generated by a normal distribution instead of shuffling the original observations among groups. This is a little stronger assumption than in the permutation approach but makes it possible to study Type I error rates, power, and to explore a process that is similar to how statistical results are generated and used in academic research settings.</p>
<p>Now let’s suppose that we are interested in what happens when we do ten independent studies of the same research question. You could think of this as ten different researchers conducting their own studies of the same topic (say passing distance) or ten times the same researchers did the same study or (less obviously) a researcher focusing on ten different response variables in the same study<a href="#fn49" class="footnote-ref" id="fnref49"><sup>49</sup></a>. Now suppose that one of two things happens with these ten unique response variables – we just report one of them (any could be used, but suppose the first one is selected) OR we only report the one of the ten with the smallest p-value. This would correspond to reporting the results of <em>a</em> study or to reporting the “most significant” of ten tries at (or in) the same study – either because nine researchers decided not to publish/ got their papers rejected by journals or because one researcher put the other nine results into their drawer of “failed studies” and never even tried to report the results.</p>
<p>The following code generates one realization of this process to explore both the p-values that are created and the estimated differences. To simulate new observations with the null hypothesis true, there are two new ideas to consider. First, we need to fit a model that makes the means the same in both groups. This is called the “mean-only” model and is implemented with <code>lm(y ~ 1, data = ...)</code>, with the <code>~ 1</code> indicating that no predictor variable is used and that a common mean is considered for all observations. Note that this notation also works in the <code>favstats</code> function to get summary statistics for the response variable without splitting it apart based on a grouping variable. In the <span class="math inline">\(n = 30\)</span> passing distance data set, the mean of all the observations is 116.04 cm and this estimate is present in the <code>(Intercept)</code> row in the <code>lm_commonmean</code> model summary.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="2.8-section2-8.html#cb136-1" tabindex="-1"></a>lm_commonmean <span class="ot">&lt;-</span> <span class="fu">lm</span>(Distance <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> ddsub)</span>
<span id="cb136-2"><a href="2.8-section2-8.html#cb136-2" tabindex="-1"></a><span class="fu">summary</span>(lm_commonmean)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Distance ~ 1, data = ddsub)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -108.038  -17.038   -0.038   16.962  128.962 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 116.0379     0.7361   157.6   &lt;2e-16
## 
## Residual standard error: 29.77 on 1635 degrees of freedom</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="2.8-section2-8.html#cb138-1" tabindex="-1"></a><span class="fu">favstats</span>(Distance <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> ddsub)</span></code></pre></div>
<pre><code>##   1 min Q1 median  Q3 max     mean       sd    n missing
## 1 1   8 99    116 133 245 116.0379 29.77388 1636       0</code></pre>
<p>The second new R code needed is the <code>simulate</code> function that can be applied to <code>lm</code>-objects; it generates a new data set that contains the same number of observations as the original one but assumes that all the aspects of the estimated model (mean(s), variance, and normal distributions) are true to generate the new observations. In this situation that implies generating new observations with the same mean (116.04) and standard deviation (29.77, also found as the “residual standard error” in the model summary). The new responses are stored in <code>SimDistance</code> in <code>ddsub</code> and then plotted in Figure <a href="2.8-section2-8.html#fig:Figure2-18">2.18</a>.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure2-18"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-18-1.png" alt="Pirate-plot of a simulated data set that assumes the same mean for both groups. The means in the two groups are very similar." width="75%" />
<p class="caption">
Figure 2.18: Pirate-plot of a simulated data set that assumes the same mean for both groups. The means in the two groups are very similar.
</p>
</div>
<p>The following code chunk generates one run through generating ten data sets as the loop works through the index <code>c</code>, simulates a new set of responses (<code>ddsub$SimDistance</code>), fits a model that explores the difference in the means of the two groups (<code>lm_sim</code>), and extracts the ten p-values (stored in <code>pval10</code>) and estimated difference in the means (stored in <code>diff10</code>). The smallest p-value of the ten p-values (<code>min(pval10)</code>) is 0.00576. By finding the value of <code>diff10</code> where <code>pval10</code> is equal to (<code>==</code>) the <code>min(pval10)</code>, the estimated difference in the means from the simulated responses that produced the smallest p-value can be extracted. The difference was -4.17 here. As in the previous initial explorations of permutations, this is just one realization of this process and it needs to be repeated many times to study the impacts of using (1) the first realization of the responses to estimate the difference and p-value and (2) the result with the smallest p-value from ten different realizations of the responses to estimate the difference and p-value. In the following code, we added
octothorpes (#)<a href="#fn50" class="footnote-ref" id="fnref50"><sup>50</sup></a> and then some text to explain what is being calculated. In computer code, octothorpes
provide a way of adding comments that tell the software (here R) to ignore any
text after a “#” on a given line. In the color version of the text, comments are
even more clearly distinguished.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="2.8-section2-8.html#cb140-1" tabindex="-1"></a><span class="co"># For one iteration through generating 10 data sets:</span></span>
<span id="cb140-2"><a href="2.8-section2-8.html#cb140-2" tabindex="-1"></a>diff10 <span class="ot">&lt;-</span> pval10 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">10</span>) <span class="co">#Create empty vectors to store 10 results</span></span>
<span id="cb140-3"><a href="2.8-section2-8.html#cb140-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">222</span>)</span>
<span id="cb140-4"><a href="2.8-section2-8.html#cb140-4" tabindex="-1"></a><span class="co"># Create 10 data sets, keep estimated differences and p-values in diff10 and pval10</span></span>
<span id="cb140-5"><a href="2.8-section2-8.html#cb140-5" tabindex="-1"></a><span class="cf">for</span> (c <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)){</span>
<span id="cb140-6"><a href="2.8-section2-8.html#cb140-6" tabindex="-1"></a>  ddsub<span class="sc">$</span>SimDistance <span class="ot">&lt;-</span> <span class="fu">simulate</span>(lm_commonmean)[[<span class="dv">1</span>]]</span>
<span id="cb140-7"><a href="2.8-section2-8.html#cb140-7" tabindex="-1"></a>  <span class="co"># Estimate two group model using simulated responses</span></span>
<span id="cb140-8"><a href="2.8-section2-8.html#cb140-8" tabindex="-1"></a>  lm_sim <span class="ot">&lt;-</span> <span class="fu">lm</span>(SimDistance <span class="sc">~</span> Condition, <span class="at">data =</span> ddsub) </span>
<span id="cb140-9"><a href="2.8-section2-8.html#cb140-9" tabindex="-1"></a>  diff10[c] <span class="ot">&lt;-</span> <span class="fu">coef</span>(lm_sim)[<span class="dv">2</span>]</span>
<span id="cb140-10"><a href="2.8-section2-8.html#cb140-10" tabindex="-1"></a>  pval10[c] <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_sim)<span class="sc">$</span>coef[<span class="dv">2</span>,<span class="dv">4</span>]</span>
<span id="cb140-11"><a href="2.8-section2-8.html#cb140-11" tabindex="-1"></a>}</span>
<span id="cb140-12"><a href="2.8-section2-8.html#cb140-12" tabindex="-1"></a>  </span>
<span id="cb140-13"><a href="2.8-section2-8.html#cb140-13" tabindex="-1"></a><span class="fu">tibble</span>(pval10, diff10)  </span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    pval10[,1] diff10[,1]
##         &lt;dbl&gt;      &lt;dbl&gt;
##  1    0.735      -0.492 
##  2    0.326       1.44  
##  3    0.158      -2.06  
##  4    0.265      -1.66  
##  5    0.153       2.09  
##  6    0.00576    -4.17  
##  7    0.915       0.160 
##  8    0.313      -1.50  
##  9    0.983       0.0307
## 10    0.268      -1.69</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="2.8-section2-8.html#cb142-1" tabindex="-1"></a><span class="fu">min</span>(pval10) <span class="co">#Smallest of 10 p-values</span></span></code></pre></div>
<pre><code>## [1] 0.005764602</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="2.8-section2-8.html#cb144-1" tabindex="-1"></a>diff10[pval10 <span class="sc">==</span> <span class="fu">min</span>(pval10)] <span class="co">#Estimated difference for data set with smallest p-value</span></span></code></pre></div>
<pre><code>## [1] -4.170526</code></pre>
<p>In these results, the first data set shows little evidence against the null hypothesis with a p-value of 0.735 and an estimated difference of -0.49. But if you repeat this process and focus just on the “top” p-value result, you think that there is moderate evidence against the null hypothesis with a p-value from the sixth data set due to its p-value of 0.0057. Remember that these are all data sets simulated with the null hypothesis being true, so we should not reject the null hypothesis. But we would expect an occasional false detection (Type I error – rejecting the null hypothesis when it is true) due to sampling variability in the data sets. But by exploring many results and selecting a single result from that suite of results (and not accounting for that selection process in the results), there is a clear issue with exaggerating the strength of evidence. While not obvious yet, we also create an issue with the estimated mean difference in the groups that is demonstrated below.</p>
<p>To fully explore the impacts of either the office drawer or publication bias (they basically have the same impacts on published results even though they are different mechanisms), this process must be repeated many times. The code is a bit more complex here, as the previous code that created ten data sets needs to be replicated <em>B</em> = 1,000 times and four sets of results stored (estimated mean differences and p-values for the first data set and the smallest p-value one). This involves a loop that is very similar to our permutation loop but with more activity inside that loop, with the code for generating and extracting the realization of ten results repeated <em>B</em> times. Figure <a href="2.8-section2-8.html#fig:Figure2-19">2.19</a> contains the results for the simulation study. In the left plot that contains the p-values we can immediately see some important differences in the distribution of p-values. In the “first” result, the p-values are evenly spread from 0 to 1 – this is what happens when the null hypothesis is true and you simulate from that scenario one time and track the p-values. A good testing method should make a mistake at the <span class="math inline">\(\alpha\)</span>-level at a rate around <span class="math inline">\(\alpha\)</span> (a 5% significance level test should make a mistake 5% of the time). If the p-values are evenly spread from 0 to 1, then about 0.05 will be between 0 and 0.05 (think of areas in rectangles with a height of 1 where the total area from 0 to 1 has to add up to 1). But when a researcher focuses only on the top result of ten, then the p-value distribution is smashed toward 0. Using <code>favstats</code> on each distribution of p-values shows that the median for the p-values from taking the first result is around 0.5 but for taking the minimum of ten results, the median p-value is 0.065. So half the results are at the “moderate” evidence level or better when selection of results is included. This gets even worse as more results are explored but seems quite problematic here.</p>
<p>The estimated difference in the means also presents an interesting story. When just reporting the first result, the distribution of the estimated means in panel b of Figure <a href="2.8-section2-8.html#fig:Figure2-19">2.19</a> shows a symmetric distribution that is centered around 0 with results extending just past <span class="math inline">\(\pm\)</span> 4 in each tail. When selection of results is included, only more extreme estimated differences are considered and no results close to 0 are even reported. There are two modes here around <span class="math inline">\(\pm\)</span> 2.5 and multiple results close to <span class="math inline">\(\pm\)</span> 5 are observed. Interestingly, the mean of both distributions is close to 0 so both are “unbiased” <a href="#fn51" class="footnote-ref" id="fnref51"><sup>51</sup></a> estimators but the distribution for the estimated difference from the selected “top” result is clearly flawed and would not give correct inferences for differences when the null hypothesis is correct. If a one-sided test had been employed, the selection of the top result would result is a clearly biased estimator as only one of the two modes would be selected. The presentation of these results is a great example of why pirate-plots are better than boxplots as a boxplot of these results would not allow the viewer to notice the two distinct groups of results.</p>

<!-- \newpage -->
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure2-19"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-19-1.png" alt="Pirate-plot of a simulation study results. Panel (a) contains the B = 1,000 p-values and (b) contains the B = 1,000 estimated differences in the means. Note that the estimated means and confidence intervals normally present in pirate-plots are suppressed here with inf.f.o = 0, inf.b.o = 0, avg.line.o = 0 because these plots are being used to summarize simulation results instead of an original data set." width="75%" />
<p class="caption">
Figure 2.19: Pirate-plot of a simulation study results. Panel (a) contains the <em>B</em> = 1,000 p-values and (b) contains the <em>B</em> = 1,000 estimated differences in the means. Note that the estimated means and confidence intervals normally present in pirate-plots are suppressed here with <code>inf.f.o = 0, inf.b.o = 0, avg.line.o = 0</code> because these plots are being used to summarize simulation results instead of an original data set.
</p>
</div>
<div style="page-break-after: always;"></div>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="2.8-section2-8.html#cb146-1" tabindex="-1"></a><span class="co"># Simulation study of generating 10 data sets and either using the first</span></span>
<span id="cb146-2"><a href="2.8-section2-8.html#cb146-2" tabindex="-1"></a><span class="co"># or &quot;best p-value&quot; result:</span></span>
<span id="cb146-3"><a href="2.8-section2-8.html#cb146-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb146-4"><a href="2.8-section2-8.html#cb146-4" tabindex="-1"></a></span>
<span id="cb146-5"><a href="2.8-section2-8.html#cb146-5" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="co"># # of simulations</span></span>
<span id="cb146-6"><a href="2.8-section2-8.html#cb146-6" tabindex="-1"></a><span class="co"># To store results</span></span>
<span id="cb146-7"><a href="2.8-section2-8.html#cb146-7" tabindex="-1"></a>Diffmeans <span class="ot">&lt;-</span> pvalues <span class="ot">&lt;-</span> Diffmeans_Min <span class="ot">&lt;-</span> pvalues_Min <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> B) </span>
<span id="cb146-8"><a href="2.8-section2-8.html#cb146-8" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span>B)){ <span class="co">#Simulation study loop to repeat process B times</span></span>
<span id="cb146-9"><a href="2.8-section2-8.html#cb146-9" tabindex="-1"></a>  <span class="co"># Create empty vectors to store 10 results for each b</span></span>
<span id="cb146-10"><a href="2.8-section2-8.html#cb146-10" tabindex="-1"></a>  diff10 <span class="ot">&lt;-</span> pval10 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">10</span>) </span>
<span id="cb146-11"><a href="2.8-section2-8.html#cb146-11" tabindex="-1"></a>  <span class="cf">for</span> (c <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)){ <span class="co">#Loop to create 10 data sets and extract results</span></span>
<span id="cb146-12"><a href="2.8-section2-8.html#cb146-12" tabindex="-1"></a>    ddsub<span class="sc">$</span>SimDistance <span class="ot">&lt;-</span> <span class="fu">simulate</span>(lm_commonmean)[[<span class="dv">1</span>]]</span>
<span id="cb146-13"><a href="2.8-section2-8.html#cb146-13" tabindex="-1"></a>    <span class="co"># Estimate two group model using simulated responses</span></span>
<span id="cb146-14"><a href="2.8-section2-8.html#cb146-14" tabindex="-1"></a>    lm_sim <span class="ot">&lt;-</span> <span class="fu">lm</span>(SimDistance <span class="sc">~</span> Condition, <span class="at">data =</span> ddsub) </span>
<span id="cb146-15"><a href="2.8-section2-8.html#cb146-15" tabindex="-1"></a>    diff10[c] <span class="ot">&lt;-</span> <span class="fu">coef</span>(lm_sim)[<span class="dv">2</span>]</span>
<span id="cb146-16"><a href="2.8-section2-8.html#cb146-16" tabindex="-1"></a>    pval10[c] <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_sim)<span class="sc">$</span>coef[<span class="dv">2</span>,<span class="dv">4</span>]</span>
<span id="cb146-17"><a href="2.8-section2-8.html#cb146-17" tabindex="-1"></a>  }</span>
<span id="cb146-18"><a href="2.8-section2-8.html#cb146-18" tabindex="-1"></a>  </span>
<span id="cb146-19"><a href="2.8-section2-8.html#cb146-19" tabindex="-1"></a>  pvalues[b] <span class="ot">&lt;-</span> pval10[<span class="dv">1</span>] <span class="co">#Store first result p-value</span></span>
<span id="cb146-20"><a href="2.8-section2-8.html#cb146-20" tabindex="-1"></a>  Diffmeans[b] <span class="ot">&lt;-</span> diff10[<span class="dv">1</span>] <span class="co">#Store first result estimated difference</span></span>
<span id="cb146-21"><a href="2.8-section2-8.html#cb146-21" tabindex="-1"></a>  </span>
<span id="cb146-22"><a href="2.8-section2-8.html#cb146-22" tabindex="-1"></a>  pvalues_Min[b] <span class="ot">&lt;-</span> <span class="fu">min</span>(pval10) <span class="co">#Store smallest p-value</span></span>
<span id="cb146-23"><a href="2.8-section2-8.html#cb146-23" tabindex="-1"></a>  Diffmeans_Min[b] <span class="ot">&lt;-</span> diff10[pval10 <span class="sc">==</span> <span class="fu">min</span>(pval10)] <span class="co">#Store est. diff of smallest p-value</span></span>
<span id="cb146-24"><a href="2.8-section2-8.html#cb146-24" tabindex="-1"></a>  </span>
<span id="cb146-25"><a href="2.8-section2-8.html#cb146-25" tabindex="-1"></a>}</span>
<span id="cb146-26"><a href="2.8-section2-8.html#cb146-26" tabindex="-1"></a></span>
<span id="cb146-27"><a href="2.8-section2-8.html#cb146-27" tabindex="-1"></a><span class="co"># Put results together</span></span>
<span id="cb146-28"><a href="2.8-section2-8.html#cb146-28" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">pvalue_results =</span> <span class="fu">c</span>(pvalues,pvalues_Min), </span>
<span id="cb146-29"><a href="2.8-section2-8.html#cb146-29" tabindex="-1"></a>                  <span class="at">Diffmeans_results =</span> <span class="fu">c</span>(Diffmeans, Diffmeans_Min), </span>
<span id="cb146-30"><a href="2.8-section2-8.html#cb146-30" tabindex="-1"></a>                  <span class="at">Scenario =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;First&quot;</span>, <span class="st">&quot;Min&quot;</span>), <span class="at">each =</span> B))</span>
<span id="cb146-31"><a href="2.8-section2-8.html#cb146-31" tabindex="-1"></a></span>
<span id="cb146-32"><a href="2.8-section2-8.html#cb146-32" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co">#Plot results</span></span>
<span id="cb146-33"><a href="2.8-section2-8.html#cb146-33" tabindex="-1"></a><span class="fu">pirateplot</span>(pvalue_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results, <span class="at">inf.f.o =</span> <span class="dv">0</span>, <span class="at">inf.b.o =</span> <span class="dv">0</span>,</span>
<span id="cb146-34"><a href="2.8-section2-8.html#cb146-34" tabindex="-1"></a>           <span class="at">avg.line.o =</span> <span class="dv">0</span>, <span class="at">main =</span> <span class="st">&quot;(a) P-value results&quot;</span>)</span>
<span id="cb146-35"><a href="2.8-section2-8.html#cb146-35" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.05</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb146-36"><a href="2.8-section2-8.html#cb146-36" tabindex="-1"></a><span class="fu">pirateplot</span>(Diffmeans_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results, <span class="at">inf.f.o =</span> <span class="dv">0</span>, <span class="at">inf.b.o =</span> <span class="dv">0</span>,</span>
<span id="cb146-37"><a href="2.8-section2-8.html#cb146-37" tabindex="-1"></a>           <span class="at">avg.line.o =</span> <span class="dv">0</span>, <span class="at">main =</span> <span class="st">&quot;(b) Estimated difference in mean results&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="2.8-section2-8.html#cb147-1" tabindex="-1"></a><span class="co"># Numerical summaries of results</span></span>
<span id="cb147-2"><a href="2.8-section2-8.html#cb147-2" tabindex="-1"></a><span class="fu">favstats</span>(pvalue_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results)</span></code></pre></div>
<pre><code>##   Scenario          min         Q1    median        Q3       max       mean         sd    n missing
## 1    First 0.0017051496 0.27075755 0.5234412 0.7784957 0.9995293 0.51899179 0.28823469 1000       0
## 2      Min 0.0005727895 0.02718018 0.0646370 0.1273880 0.5830232 0.09156364 0.08611836 1000       0</code></pre>
<!-- \newpage -->
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="2.8-section2-8.html#cb149-1" tabindex="-1"></a><span class="fu">favstats</span>(Diffmeans_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results)</span></code></pre></div>
<pre><code>##   Scenario       min         Q1     median       Q3      max       mean       sd    n missing
## 1    First -4.531864 -0.8424604 0.07360378 1.002228 4.458951 0.05411473 1.392940 1000       0
## 2      Min -5.136510 -2.6857436 1.24042295 2.736930 5.011190 0.03539750 2.874454 1000       0</code></pre>
<div style="page-break-after: always;"></div>
<p>Generally, the challenge in this situation is that if you perform many tests (ten were the focus before) at the same time (instead of just one test), you inflate the
Type I error rate across the tests.
We can define the <strong><em>family-wise error rate</em></strong>
as the probability that at least one error is made on a set of tests or, more
compactly, Pr(At least 1 error is made) where Pr() is the probability of an
event occurring. The family-wise error is meant to capture the overall
situation in terms of measuring the likelihood of making a mistake if we
consider many tests, each with some chance of making their own mistake, and
focus on how often we make at least one error when we do many tests. A quick
probability calculation shows the magnitude of the problem. If we start with a
5% significance level test, then Pr(Type I error on one test) = 0.05 and the Pr(no
errors made on one test) = 0.95, by definition. This is our standard hypothesis
testing situation. Now, suppose we have <span class="math inline">\(m\)</span> independent tests, then</p>
<p><span class="math display">\[\begin{array}{ll}
&amp; \text{Pr(make at least 1 Type I error given all null hypotheses are true)} \\
&amp; = 1 - \text{Pr(no errors made)} \\
&amp; = 1 - 0.95^m.
\end{array}\]</span></p>
<p>Figure <a href="2.8-section2-8.html#fig:Figure2-20">2.20</a> shows how the probability of having at least one
false detection grows rapidly with the number of tests, <span class="math inline">\(m\)</span>. The plot stops at 100
tests since it is effectively a 100% chance of at least one false detection.
It might seem like doing 100 tests is a lot, but, as mentioned before, some researchers consider situations where millions of tests are
considered. Researchers want to make sure that when they report a “significant” result that
it is really likely to be a real result and will show up as a difference in the
next data set they collect. Some researchers are now collecting multiple data
sets to use in a single study and using one data set to identify interesting
results and then using a validation or test data set that they withheld from
initial analysis to try to verify that the first results are also present in that
second data set. This also has problems but the only way to develop an understanding of a process is to look across a suite of studies and learn from that accumulation of evidence. This is a good start but needs to be coupled with complete reporting of all results, even those that have p-values larger than 0.05 to avoid the bias identified in the previous simulation study.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure2-20"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-20-1.png" alt="Plot of family-wise error rate (bold solid line) as the number of tests performed increases. Dashed line indicates 0.05 and grey solid line highlights the probability of at least on error on \(m = 10\) tests." width="75%" />
<p class="caption">
Figure 2.20: Plot of family-wise error rate (bold solid line) as the number of tests performed increases. Dashed line indicates 0.05 and grey solid line highlights the probability of at least on error on <span class="math inline">\(m = 10\)</span> tests.
</p>
</div>
<p>All hope is not lost when multiple tests are being considered in the same study or by a researcher and exploring more than one result need not lead to clearly biased and flawed results being reported. To account for multiple testing in the same study/analysis, there are many approaches that adjust results to acknowledge that multiple tests are being considered. A simple approach called the “Bonferroni Correction” <span class="citation">(<a href="#ref-Bland1995">Bland and Altman 1995</a>)</span> is a good starting point for learning about these methods. It works to control the family-wise error rate of a suite of tests by either dividing <span class="math inline">\(\alpha\)</span> by the number of tests (<span class="math inline">\(\alpha/m\)</span>) or, equivalently and more usefully, multiplying the p-value by the number of tests being considered (<span class="math inline">\(p-value_{adjusted} = p-value \cdot m\)</span> or <span class="math inline">\(1\)</span> if <span class="math inline">\(p-value \cdot m &gt; 1\)</span>). The “Bonferroni adjusted p-values” are then used as regular p-values to assess evidence against each null hypothesis but now accounting for exploring many of them together. There are some assumptions that this adjustment method makes that make it to generally be a conservative adjustment method. In particular, it assumes that all <span class="math inline">\(m\)</span> tests are independent of each other and that the null hypothesis was true for all <span class="math inline">\(m\)</span> tests conducted. While all p-values should be reported in this situation when considering ten results, the impacts of using a Bonferroni correction are that the resulting p-values are not driving inflated Type I error rates even if the smallest p-value is the main focus of the results. The correction also provides a suggestion of decreasing evidence in the first test result because it is now incorporated in considering ten results instead of one.</p>
<p>The following code repeats the simulation study but with the p-values adjusted for multiple testing within each simulation but does not repeat tracking the estimated differences in the means as this is not impacted by the p-value adjustment process. The <code>p.adjust</code> function provides Bonferroni corrections to a vector of p-values (here ten are collected together) using the <code>bonferroni</code> method option (<code>p.adjust(pval10, method = "bonferroni")</code>) and then stores those results. Figure <a href="2.8-section2-8.html#fig:Figure2-21">2.21</a> shows the results for the first result and minimum result again, but now with these corrections incorporated. The plots may look a bit odd, but in the first data set, so many of the first data sets had p-values that were “large” that they were adjusted to have p-values of 1 (so no evidence against the null once we account for multiple testing). The distribution for the minimum p-value results with adjustment more closely resembles the distribution of the first result p-values from Figure <a href="2.8-section2-8.html#fig:Figure2-19">2.19</a>, except for some minor clumping up at adjusted p-values of 1.</p>
<!-- \newpage -->

<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="2.8-section2-8.html#cb151-1" tabindex="-1"></a><span class="co"># Simulation study of generating 10 data sets and either using the first </span></span>
<span id="cb151-2"><a href="2.8-section2-8.html#cb151-2" tabindex="-1"></a><span class="co"># or &quot;best p-value&quot; result:</span></span>
<span id="cb151-3"><a href="2.8-section2-8.html#cb151-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb151-4"><a href="2.8-section2-8.html#cb151-4" tabindex="-1"></a></span>
<span id="cb151-5"><a href="2.8-section2-8.html#cb151-5" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="co"># # of simulations</span></span>
<span id="cb151-6"><a href="2.8-section2-8.html#cb151-6" tabindex="-1"></a>pvalues <span class="ot">&lt;-</span> pvalues_Min <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> B) <span class="co">#To store results</span></span>
<span id="cb151-7"><a href="2.8-section2-8.html#cb151-7" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span>B)){ <span class="co">#Simulation study loop to repeat process B times</span></span>
<span id="cb151-8"><a href="2.8-section2-8.html#cb151-8" tabindex="-1"></a>  <span class="co"># Create empty vectors to store 10 results for each b</span></span>
<span id="cb151-9"><a href="2.8-section2-8.html#cb151-9" tabindex="-1"></a>  pval10 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> <span class="dv">10</span>) </span>
<span id="cb151-10"><a href="2.8-section2-8.html#cb151-10" tabindex="-1"></a>  <span class="cf">for</span> (c <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)){ <span class="co">#Loop to create 10 data sets and extract results</span></span>
<span id="cb151-11"><a href="2.8-section2-8.html#cb151-11" tabindex="-1"></a>    ddsub<span class="sc">$</span>SimDistance <span class="ot">&lt;-</span> <span class="fu">simulate</span>(lm_commonmean)[[<span class="dv">1</span>]]</span>
<span id="cb151-12"><a href="2.8-section2-8.html#cb151-12" tabindex="-1"></a>    <span class="co"># Estimate two group model using simulated responses</span></span>
<span id="cb151-13"><a href="2.8-section2-8.html#cb151-13" tabindex="-1"></a>    lm_sim <span class="ot">&lt;-</span> <span class="fu">lm</span>(SimDistance <span class="sc">~</span> Condition, <span class="at">data =</span> ddsub) </span>
<span id="cb151-14"><a href="2.8-section2-8.html#cb151-14" tabindex="-1"></a>    pval10[c] <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_sim)<span class="sc">$</span>coef[<span class="dv">2</span>,<span class="dv">4</span>]</span>
<span id="cb151-15"><a href="2.8-section2-8.html#cb151-15" tabindex="-1"></a>  }</span>
<span id="cb151-16"><a href="2.8-section2-8.html#cb151-16" tabindex="-1"></a>  </span>
<span id="cb151-17"><a href="2.8-section2-8.html#cb151-17" tabindex="-1"></a>  pval10 <span class="ot">&lt;-</span> <span class="fu">p.adjust</span>(pval10, <span class="at">method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span>
<span id="cb151-18"><a href="2.8-section2-8.html#cb151-18" tabindex="-1"></a>  </span>
<span id="cb151-19"><a href="2.8-section2-8.html#cb151-19" tabindex="-1"></a>  pvalues[b] <span class="ot">&lt;-</span> pval10[<span class="dv">1</span>] <span class="co">#Store first result adjusted p-value</span></span>
<span id="cb151-20"><a href="2.8-section2-8.html#cb151-20" tabindex="-1"></a>  </span>
<span id="cb151-21"><a href="2.8-section2-8.html#cb151-21" tabindex="-1"></a>  pvalues_Min[b] <span class="ot">&lt;-</span> <span class="fu">min</span>(pval10) <span class="co">#Store smallest adjusted p-value</span></span>
<span id="cb151-22"><a href="2.8-section2-8.html#cb151-22" tabindex="-1"></a>}</span>
<span id="cb151-23"><a href="2.8-section2-8.html#cb151-23" tabindex="-1"></a></span>
<span id="cb151-24"><a href="2.8-section2-8.html#cb151-24" tabindex="-1"></a><span class="co"># Put results together</span></span>
<span id="cb151-25"><a href="2.8-section2-8.html#cb151-25" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">pvalue_results =</span> <span class="fu">c</span>(pvalues, pvalues_Min), </span>
<span id="cb151-26"><a href="2.8-section2-8.html#cb151-26" tabindex="-1"></a>                  <span class="at">Scenario =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;First&quot;</span>, <span class="st">&quot;Min&quot;</span>), <span class="at">each =</span> B))</span>
<span id="cb151-27"><a href="2.8-section2-8.html#cb151-27" tabindex="-1"></a></span>
<span id="cb151-28"><a href="2.8-section2-8.html#cb151-28" tabindex="-1"></a><span class="fu">pirateplot</span>(pvalue_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results, <span class="at">inf.f.o =</span> <span class="dv">0</span>, <span class="at">inf.b.o =</span> <span class="dv">0</span>,</span>
<span id="cb151-29"><a href="2.8-section2-8.html#cb151-29" tabindex="-1"></a>           <span class="at">avg.line.o =</span> <span class="dv">0</span>, <span class="at">main =</span> <span class="st">&quot;P-value results&quot;</span>)</span>
<span id="cb151-30"><a href="2.8-section2-8.html#cb151-30" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.05</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure2-21"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-21-1.png" alt="Pirate-plot of a simulation study results of p-values with Bonferroni correction." width="75%" />
<p class="caption">
Figure 2.21: Pirate-plot of a simulation study results of p-values with Bonferroni correction.
</p>
</div>
<div style="page-break-after: always;"></div>
<p>By applying the <code>pdata</code> function to the two groups of results, we can directly assess how many of each type (“First” or “Min”) resulted in p-values less than 0.05. It ends up that if we adjust for ten tests and just focus on the first result, it is really hard to find moderate or strong evidence against the null hypothesis as only 3 in 1,000 results had adjusted p-values less than 0.05. When the focus is on the “best” (or minimum) p-value result when ten are considered and adjustments are made, 52 out of 1,000 results (0.052) show at least moderate evidence against the null hypothesis. This is the rate we would expect from a well-behaved hypothesis test when the null hypothesis is true – that we would only make a mistake 5% of the time when <span class="math inline">\(\alpha\)</span> is 0.05.</p>
<!-- \newpage -->
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="2.8-section2-8.html#cb152-1" tabindex="-1"></a><span class="co"># Numerical summaries of results</span></span>
<span id="cb152-2"><a href="2.8-section2-8.html#cb152-2" tabindex="-1"></a><span class="fu">favstats</span>(pvalue_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results)</span></code></pre></div>
<pre><code>##   Scenario         min        Q1  median Q3 max      mean        sd    n missing
## 1    First 0.017051496 1.0000000 1.00000  1   1 0.9628911 0.1502805 1000       0
## 2      Min 0.005727895 0.2718018 0.64637  1   1 0.6212932 0.3597701 1000       0</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="2.8-section2-8.html#cb154-1" tabindex="-1"></a><span class="co"># Proportion of simulations with adjusted p-values less than 0.05</span></span>
<span id="cb154-2"><a href="2.8-section2-8.html#cb154-2" tabindex="-1"></a><span class="fu">pdata</span>(pvalue_results <span class="sc">~</span> Scenario, <span class="at">data =</span> results, .<span class="dv">05</span>, <span class="at">lower.tail =</span> T)</span></code></pre></div>
<pre><code>##   Scenario pdata_v
## 1    First   0.003
## 2      Min   0.052</code></pre>
<p>So adjusting for multiple testing is suggested when multiple tests are being considered “simultaneously”. The Bonferroni adjustment is easy but also crude and can be conservative in applications, especially when the number of tests grows very large (think of multiplying all your p-values by <span class="math inline">\(m\)</span> = 1,000,000). So other approaches are considered in situations with many tests (there are six other options in the <code>p.adjust</code> function and other functions for doing similar things in R) and there are other approaches that are customized for particular situations with one example discussed in Chapter <a href="3-chapter3.html#chapter3">3</a>. The biggest lesson as a statistics student to take from this is that all results are of interest and should be reported and that adjustment of p-values should be considered in studies where many results are being considered. If you are reading results that seem to have walked discretely around these issues you should be suspicious of the real strength of their evidence.</p>
<p>While it wasn’t used here, the same general code used to explore this multiple testing issue could be used to explore the power of a particular procedure. If simulations were created from a model with a difference in the means in the groups, then the null hypothesis would have been false and the rate of correctly rejecting the null hypothesis could be studied. The rate of correct rejections is the <em>power</em> of a procedure for a chosen version of a true alternative hypothesis (there are many ways to have it be true and you have to choose one to study power) and simply switching the model being simulated from would allow that to be explored. We could also use similar code to compare the power and Type I error rates of parametric versus permutation procedures or to explore situations where an assumption is not true. The steps would be similar – decide on what you need to simulate from and track a quantity of interest across repeated simulated data sets.</p>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-Bland1995" class="csl-entry">
Bland, J Martin, and Douglas G Altman. 1995. <span>“Multiple Significance Tests: The Bonferroni Method.”</span> <em>BMJ</em> 310 (6973): 170. <a href="https://doi.org/10.1136/bmj.310.6973.170">https://doi.org/10.1136/bmj.310.6973.170</a>.
</div>
<div id="ref-Schneck2017" class="csl-entry">
Schneck, Andreas. 2017. <span>“Examining Publication Bias—a Simulation-Based Evaluation of Statistical Tests on Publication Bias.”</span> <em>PeerJ</em> 5 (November): e4115. <a href="https://doi.org/10.7717/peerj.4115">https://doi.org/10.7717/peerj.4115</a>.
</div>
<div id="ref-Smith2014" class="csl-entry">
Smith, Michael L. 2014. <span>“Honey Bee Sting Pain Index by Body Location.”</span> <em>PeerJ</em> 2 (April): e338. <a href="https://doi.org/10.7717/peerj.338">https://doi.org/10.7717/peerj.338</a>.
</div>
<div id="ref-Wasserstein2016" class="csl-entry">
Wasserstein, Ronald L., and Nicole A. Lazar. 2016. <span>“The ASA Statement on p-Values: Context, Process, and Purpose.”</span> <em>The American Statistician</em> 70 (2): 129–33. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a>.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="48">
<li id="fn48"><p>The data are provided and briefly discussed in the Practice Problems for Chapter <a href="3-chapter3.html#chapter3">3</a>.<a href="2.8-section2-8.html#fnref48" class="footnote-back">↩︎</a></p></li>
<li id="fn49"><p>Researchers often measure multiple related response variables on the same subjects while they are conducting a study, so these would not meet the “independent studies” assumption that is used here, but we can start with the assumption of independent results across these responses as the math is easier and the results are conservative. You can consult a statistician for other related approaches that incorporate the dependency of the different responses.<a href="2.8-section2-8.html#fnref49" class="footnote-back">↩︎</a></p></li>
<li id="fn50"><p>You can correctly call octothorpes <em>number</em> symbols or, in the
twitter verse, <em>hashtags</em>. For more on this symbol, see
“<a href="http://blog.dictionary.com/octothorpe/" class="uri">http://blog.dictionary.com/octothorpe/</a>”. Even after reading this, I call them
number symbols.<a href="2.8-section2-8.html#fnref50" class="footnote-back">↩︎</a></p></li>
<li id="fn51"><p>An unbiased estimator is a statistic that is on average equal to the population parameter.<a href="2.8-section2-8.html#fnref51" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="2.7-section2-7.html"><button class="btn btn-default">Previous</button></a>
<a href="2.9-section2-9.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
