<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="4.5 Observational study example: The Psychology of Debt | Intermediate Statistics with R" />
<meta property="og:type" content="book" />


<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="4.5 Observational study example: The Psychology of Debt | Intermediate Statistics with R">

<title>4.5 Observational study example: The Psychology of Debt | Intermediate Statistics with R</title>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if bootstrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover" id="toc-cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments" id="toc-acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1" id="toc-chapter1"><span class="toc-section-number">1</span> Preface</a>
<ul>
<li><a href="1.1-section1-1.html#section1-1" id="toc-section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1.2-section1-2.html#section1-2" id="toc-section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1.3-section1-3.html#section1-3" id="toc-section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1.4-section1-4.html#section1-4" id="toc-section1-4"><span class="toc-section-number">1.4</span> R Markdown</a></li>
<li><a href="1.5-section1-5.html#section1-5" id="toc-section1-5"><span class="toc-section-number">1.5</span> Grammar of Graphics</a></li>
<li><a href="1.6-section1-6.html#section1-6" id="toc-section1-6"><span class="toc-section-number">1.6</span> Exiting RStudio</a></li>
<li><a href="1.7-section1-7.html#section1-7" id="toc-section1-7"><span class="toc-section-number">1.7</span> Chapter summary</a></li>
<li><a href="1.8-section1-8.html#section1-8" id="toc-section1-8"><span class="toc-section-number">1.8</span> Summary of important R code</a></li>
<li><a href="1.9-section1-9.html#section1-9" id="toc-section1-9"><span class="toc-section-number">1.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2" id="toc-chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a>
<ul>
<li><a href="2.1-section2-1.html#section2-1" id="toc-section2-1"><span class="toc-section-number">2.1</span> Data wrangling and density curves</a></li>
<li><a href="2.2-section2-2.html#section2-2" id="toc-section2-2"><span class="toc-section-number">2.2</span> Pirate-plots</a></li>
<li><a href="2.3-section2-3.html#section2-3" id="toc-section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2.4-section2-4.html#section2-4" id="toc-section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2.5-section2-5.html#section2-5" id="toc-section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2.6-section2-6.html#section2-6" id="toc-section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2.7-section2-7.html#section2-7" id="toc-section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2.8-section2-8.html#section2-8" id="toc-section2-8"><span class="toc-section-number">2.8</span> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</a></li>
<li><a href="2.9-section2-9.html#section2-9" id="toc-section2-9"><span class="toc-section-number">2.9</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2.10-section2-10.html#section2-10" id="toc-section2-10"><span class="toc-section-number">2.10</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2.11-section2-11.html#section2-11" id="toc-section2-11"><span class="toc-section-number">2.11</span> Chapter summary</a></li>
<li><a href="2.12-section2-12.html#section2-12" id="toc-section2-12"><span class="toc-section-number">2.12</span> Summary of important R code</a></li>
<li><a href="2.13-section2-13.html#section2-13" id="toc-section2-13"><span class="toc-section-number">2.13</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3" id="toc-chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a>
<ul>
<li><a href="3.1-section3-1.html#section3-1" id="toc-section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3.2-section3-2.html#section3-2" id="toc-section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell means and reference-coding)</a></li>
<li><a href="3.3-section3-3.html#section3-3" id="toc-section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3.4-section3-4.html#section3-4" id="toc-section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3.5-section3-5.html#section3-5" id="toc-section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3.6-section3-6.html#section3-6" id="toc-section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3.7-section3-7.html#section3-7" id="toc-section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for the Overtake data</a></li>
<li><a href="3.8-section3-8.html#section3-8" id="toc-section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3.9-section3-9.html#section3-9" id="toc-section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3.10-section3-10.html#section3-10" id="toc-section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4" id="toc-chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a>
<ul>
<li><a href="4.1-section4-1.html#section4-1" id="toc-section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4.2-section4-2.html#section4-2" id="toc-section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4.3-section4-3.html#section4-3" id="toc-section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4.4-section4-4.html#section4-4" id="toc-section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4.5-section4-5.html#section4-5" id="toc-section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4.6-section4-6.html#section4-6" id="toc-section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs and Estimability</a></li>
<li><a href="4.7-section4-7.html#section4-7" id="toc-section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4.8-section4-8.html#section4-8" id="toc-section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4.9-section4-9.html#section4-9" id="toc-section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5" id="toc-chapter5"><span class="toc-section-number">5</span> Chi-square tests</a>
<ul>
<li><a href="5.1-section5-1.html#section5-1" id="toc-section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and tableplots</a></li>
<li><a href="5.2-section5-2.html#section5-2" id="toc-section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5.3-section5-3.html#section5-3" id="toc-section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5.4-section5-4.html#section5-4" id="toc-section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5.5-section5-5.html#section5-5" id="toc-section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.6-section5-6.html#section5-6" id="toc-section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.7-section5-7.html#section5-7" id="toc-section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5.8-section5-8.html#section5-8" id="toc-section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5.9-section5-9.html#section5-9" id="toc-section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5.10-section5-10.html#section5-10" id="toc-section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5.11-section5-11.html#section5-11" id="toc-section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5.12-section5-12.html#section5-12" id="toc-section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5.13-section5-13.html#section5-13" id="toc-section5-13"><span class="toc-section-number">5.13</span> Summary of important R code</a></li>
<li><a href="5.14-section5-14.html#section5-14" id="toc-section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6" id="toc-chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a>
<ul>
<li><a href="6.1-section6-1.html#section6-1" id="toc-section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6.2-section6-2.html#section6-2" id="toc-section6-2"><span class="toc-section-number">6.2</span> Estimating the correlation coefficient</a></li>
<li><a href="6.3-section6-3.html#section6-3" id="toc-section6-3"><span class="toc-section-number">6.3</span> Relationships between variables by groups</a></li>
<li><a href="6.4-section6-4.html#section6-4" id="toc-section6-4"><span class="toc-section-number">6.4</span> Inference for the correlation coefficient</a></li>
<li><a href="6.5-section6-5.html#section6-5" id="toc-section6-5"><span class="toc-section-number">6.5</span> Are tree diameters related to tree heights?</a></li>
<li><a href="6.6-section6-6.html#section6-6" id="toc-section6-6"><span class="toc-section-number">6.6</span> Describing relationships with a regression model</a></li>
<li><a href="6.7-section6-7.html#section6-7" id="toc-section6-7"><span class="toc-section-number">6.7</span> Least Squares Estimation</a></li>
<li><a href="6.8-section6-8.html#section6-8" id="toc-section6-8"><span class="toc-section-number">6.8</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6.9-section6-9.html#section6-9" id="toc-section6-9"><span class="toc-section-number">6.9</span> Outliers: leverage and influence</a></li>
<li><a href="6.10-section6-10.html#section6-10" id="toc-section6-10"><span class="toc-section-number">6.10</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6.11-section6-11.html#section6-11" id="toc-section6-11"><span class="toc-section-number">6.11</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6.12-section6-12.html#section6-12" id="toc-section6-12"><span class="toc-section-number">6.12</span> Chapter summary</a></li>
<li><a href="6.13-section6-13.html#section6-13" id="toc-section6-13"><span class="toc-section-number">6.13</span> Summary of important R code</a></li>
<li><a href="6.14-section6-14.html#section6-14" id="toc-section6-14"><span class="toc-section-number">6.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7" id="toc-chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a>
<ul>
<li><a href="7.1-section7-1.html#section7-1" id="toc-section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7.2-section7-2.html#section7-2" id="toc-section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7.3-section7-3.html#section7-3" id="toc-section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7.4-section7-4.html#section7-4" id="toc-section7-4"><span class="toc-section-number">7.4</span> Randomization-based inferences for the slope coefficient</a></li>
<li><a href="7.5-section7-5.html#section7-5" id="toc-section7-5"><span class="toc-section-number">7.5</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7.6-section7-6.html#section7-6" id="toc-section7-6"><span class="toc-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7.7-section7-7.html#section7-7" id="toc-section7-7"><span class="toc-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7.8-section7-8.html#section7-8" id="toc-section7-8"><span class="toc-section-number">7.8</span> Chapter summary</a></li>
<li><a href="7.9-section7-9.html#section7-9" id="toc-section7-9"><span class="toc-section-number">7.9</span> Summary of important R code</a></li>
<li><a href="7.10-section7-10.html#section7-10" id="toc-section7-10"><span class="toc-section-number">7.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8" id="toc-chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a>
<ul>
<li><a href="8.1-section8-1.html#section8-1" id="toc-section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8.2-section8-2.html#section8-2" id="toc-section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8.3-section8-3.html#section8-3" id="toc-section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8.4-section8-4.html#section8-4" id="toc-section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8.5-section8-5.html#section8-5" id="toc-section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8.6-section8-6.html#section8-6" id="toc-section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8.7-section8-7.html#section8-7" id="toc-section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8.8-section8-8.html#section8-8" id="toc-section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8.9-section8-9.html#section8-9" id="toc-section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8.10-section8-10.html#section8-10" id="toc-section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8.11-section8-11.html#section8-11" id="toc-section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8.12-section8-12.html#section8-12" id="toc-section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8.13-section8-13.html#section8-13" id="toc-section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8.14-section8-14.html#section8-14" id="toc-section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8.15-section8-15.html#section8-15" id="toc-section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8.16-section8-16.html#section8-16" id="toc-section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8.17-section8-17.html#section8-17" id="toc-section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9" id="toc-chapter9"><span class="toc-section-number">9</span> Case studies</a>
<ul>
<li><a href="9.1-section9-1.html#section9-1" id="toc-section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9.2-section9-2.html#section9-2" id="toc-section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9.3-section9-3.html#section9-3" id="toc-section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9.4-section9-4.html#section9-4" id="toc-section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9.5-section9-5.html#section9-5" id="toc-section9-5"><span class="toc-section-number">9.5</span> What do didgeridoos really do about sleepiness?</a></li>
<li><a href="9.6-section9-6.html#section9-6" id="toc-section9-6"><span class="toc-section-number">9.6</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references" id="toc-references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section4-5" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Observational study example: The Psychology of Debt</h2>
<p>In this section, the analysis of a survey of <span class="math inline">\(N = 464\)</span> randomly sampled
adults will be analyzed from a survey conducted by <span class="citation">Lea, Webley, and Walker (<a href="#ref-Lea1995">1995</a>)</span>
and available in the <code>debt</code> data set from the <code>faraway</code> package
<span class="citation">(<a href="#ref-R-faraway">Faraway 2022</a>)</span>.
The subjects responded to a variety of questions
including whether they buy cigarettes (<code>cigbuy</code>: 0 if
no, 1 if yes), their housing situation (<code>house</code>: 1 = rent, 2 = mortgage,
and 3 = owned outright), their income group (<code>incomegp</code>: 1 =
lowest, 5 = highest), and their score on a continuous scale of attitudes about
debt (<code>prodebt</code>: 1 = least favorable, 6 = most favorable). The variable <code>prodebt</code>
was derived as the average of a series of questions about debt with each
question measured on an <strong><em>ordinal</em></strong> 1 to 6 scale, with higher values
corresponding to more positive responses about <span class="math inline">\(\underline{\text{going into debt}}\)</span>
of various kinds. The ordered scale on surveys that try to elicit your opinions on
topics with scales from 1 to 5, 1 to 6, 1 to 7 or even, sometimes, 1 to 10 is called
a <strong><em>Likert scale</em></strong> <span class="citation">(<a href="#ref-Likert1932">Likert 1932</a>)</span>. It is not a quantitative scale and really
should be handled more carefully than taking an average of a set responses as was done here. That
said, it is extremely common practice in social science research to treat ordinal
responses as if they are quantitative and take the average of many of them to
create a more continuous response variable like the one we are using here. If
you continue your statistics explorations, you will see some better techniques
for analyzing ordinal responses. That said, the scale of the
response is relatively easy to understand as an amount of willingness to go
into debt on a scale from 1 to 6 with higher values corresponding to more
willingness to be in debt.</p>
<p>These data are typical of survey data where respondents were not required
to answer all questions and there are some
missing responses. We could clean out any individuals that failed to respond to
all questions (called “complete cases”) using the <code>drop_na</code> function, which will return responses only for subjects
that responded to every question in
the data set, <code>debt</code>. The change in sample size is available by running the <code>dim</code> function on the two data sets – there were <span class="math inline">\(464\)</span> observations (rows) initially along with <span class="math inline">\(13\)</span> variables (columns) and once observations with any missing values were dropped there are <span class="math inline">\(N = 304\)</span> for us to analyze. Losing 35% of the observations is a pretty noticeable loss.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="4.5-section4-5.html#cb367-1" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb367-2"><a href="4.5-section4-5.html#cb367-2" tabindex="-1"></a><span class="fu">data</span>(debt)</span>
<span id="cb367-3"><a href="4.5-section4-5.html#cb367-3" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb367-4"><a href="4.5-section4-5.html#cb367-4" tabindex="-1"></a>debt <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(debt) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">incomegp =</span> <span class="fu">factor</span>(incomegp),</span>
<span id="cb367-5"><a href="4.5-section4-5.html#cb367-5" tabindex="-1"></a>                                   <span class="at">cigbuy =</span> <span class="fu">factor</span>(cigbuy)</span>
<span id="cb367-6"><a href="4.5-section4-5.html#cb367-6" tabindex="-1"></a>                                   )</span>
<span id="cb367-7"><a href="4.5-section4-5.html#cb367-7" tabindex="-1"></a>debtc <span class="ot">&lt;-</span> debt <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span>
<span id="cb367-8"><a href="4.5-section4-5.html#cb367-8" tabindex="-1"></a></span>
<span id="cb367-9"><a href="4.5-section4-5.html#cb367-9" tabindex="-1"></a><span class="fu">dim</span>(debt)</span></code></pre></div>
<pre><code>## [1] 464  13</code></pre>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="4.5-section4-5.html#cb369-1" tabindex="-1"></a><span class="fu">dim</span>(debtc)</span></code></pre></div>
<pre><code>## [1] 304  13</code></pre>
<p>Using <code>drop_na()</code> with a list a variable names, we can focus on the three variables we are using in this model and whether the responses are missing on them, only cleaning out rows that are missing on <code>incomegp</code>, <code>cigbuy</code>, and/or <code>prodebt</code><a href="#fn92" class="footnote-ref" id="fnref92"><sup>92</sup></a>. The missingness is less dramatic, retaining <span class="math inline">\(N = 388\)</span> observations in <code>debtRc</code> for our analysis using these three variables.</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="4.5-section4-5.html#cb371-1" tabindex="-1"></a><span class="co"># Remove rows with missing values based on just three variables.</span></span>
<span id="cb371-2"><a href="4.5-section4-5.html#cb371-2" tabindex="-1"></a>debtRc <span class="ot">&lt;-</span> debt <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(incomegp, cigbuy, prodebt)</span>
<span id="cb371-3"><a href="4.5-section4-5.html#cb371-3" tabindex="-1"></a><span class="fu">dim</span>(debtRc)</span></code></pre></div>
<pre><code>## [1] 388  13</code></pre>
<p>The second approach seems better as it drops fewer observations so we will use that below. But suppose that people did not want to
provide their income levels if they were in the lowest or highest
income groups and that is why they are missing. Then we would be missing responses systematically and conclusions
could be biased because of ignoring particular types of subjects. We don’t have particular statistical tools to easily handle this problem but every researcher should worry about non-response when selected subjects do not respond at
all or fail to answer some questions. When the missing values are systematic in some fashion and not just missing randomly (missing randomly might be thought of as caused by “demonic intrusion” <span class="citation">(<a href="#ref-Hurlbert1984">Hurlbert 1984</a>)</span> that can’t be easily explained or related to the types of responses), then we worry about <strong><em>non-response bias</em></strong> that is systematically biasing our results because of the missing responses. This also ties back into our discussion of who was sampled. We need to
think carefully about who was part of the sample but refused to participate and
how that might impact our inferences. And whether we can even address the research question of interest based on what was measured given those that refused/failed to respond. For example, suppose we are studying river flows and are interested in the height of a river. Missingness in these responses could arise because a battery fails or the data logger “crashes” (not related to the responses and so not definitely problematic) or because of something about the measurements to be taken that causes the missingness (suppose the gage can only can measure between one and three feet deep and the river is running at four feet deep during a flood or below 1 foot during a drought). The first machine failures are very different from the height-based missing responses; the height-based missingness clearly leads to bias in estimating mean river height because of what can not be observed. In Chapter <a href="5-chapter5.html#chapter5">5</a>, we introduce the <code>tableplot</code> as another tool to visualize data that can also show missing data patterns to help you think about these sorts of issues further<a href="#fn93" class="footnote-ref" id="fnref93"><sup>93</sup></a>. If you delete observations and the missing data are not random/non-systematic, your scope of inference is restricted to just those subjects that provided responses and were analyzed. If the missingness is random and not related to aspects of the measurements taken, then some missingness can be tolerated and still retain some comfort that inferences can be extended to the population a random sample of subjects was taken from.</p>
<p>Ignoring this potential for bias in the
results for the moment, we are first interested in whether buying
cigarettes/not and income groups interact in their explanation of the
respondent’s mean opinions on being in debt. The interaction plot
(Figure <a href="4.5-section4-5.html#fig:Figure4-15">4.15</a>) may suggest an interaction between <code>cigbuy</code>
and <code>incomegp</code> where the lines cross, switching which of the <code>cigbuy</code> levels is higher (income levels 2, 3, and 5) or even almost not different (income levels 1 and 4). But it is
not as clear as the previous examples, especially with how large the SEs are relative the variation in the means. The interaction <span class="math inline">\(F\)</span>-test helps us
objectively assess evidence against the null hypothesis of no interaction. Based on the plot, there do
not appear to be differences based on cigarette purchasing but there might be some
differences between the income groups if we drop the interaction from the model. If we drop the interaction, then
this suggests that we might be in Scenario 2 or 3 where a single main effect of
interest is present.</p>

<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="4.5-section4-5.html#cb373-1" tabindex="-1"></a><span class="fu">intplotarray</span>(prodebt <span class="sc">~</span> cigbuy <span class="sc">*</span> incomegp, <span class="at">data =</span> debtRc, <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-15"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-15-1.png" alt="Interaction plot array of prodebt by income group (1 to 5) and whether they buy cigarettes (0 = no, 1 = yes)." width="75%" />
<p class="caption">
Figure 4.15: Interaction plot array of <code>prodebt</code> by income group (1 to 5) and whether they buy cigarettes (0 = no, 1 = yes).
</p>
</div>
<p>As in other situations, and especially
with observational studies where a single large sample is collected and then the levels of the factor variables are observed, it is
important to check for balance – whether all the combinations of the two
predictor variables are similarly represented.
Even more critically, we need to
check whether all the combinations of levels of factors are measured. If a
combination is not measured, then we lose the ability to estimate the mean for
that combination and the ability to test for an interaction. A solution to that
problem would be to collapse the categories of one of the variables, changing
the definitions of the levels but if you fail to obtain information for all
combinations, you can’t work with the interaction model. In this situation, we
barely have enough information to proceed (the smallest <span class="math inline">\(n_{jk}\)</span> is 13 for
income group 4 that buys cigarettes). We have a very unbalanced design
with counts between 13 and 60 in the different combinations, so lose some resistance to violation of assumptions but can proceed to explore the model with a critical eye on how the diagnostic plots look.</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="4.5-section4-5.html#cb374-1" tabindex="-1"></a><span class="fu">tally</span>(cigbuy <span class="sc">~</span> incomegp, <span class="at">data =</span> debtRc)</span></code></pre></div>
<pre><code>##       incomegp
## cigbuy  1  2  3  4  5
##      0 36 49 54 53 60
##      1 37 45 20 13 21</code></pre>
<p>The test for the interaction is always
how we start our modeling in Two-Way ANOVA situations. The ANOVA table suggests
that there is little evidence against the null hypothesis of no interaction between the income level and
buying cigarettes on the opinions of the respondents towards debt
(<span class="math inline">\(F(4,378) = 0.686\)</span>, p-value = 0.6022), so we would conclude that there is likely not an interaction present here and we can drop the interaction from the model. This suggests that the initial assessment
that the interaction wasn’t too prominent
was correct. We should move to the additive model here but first need to check
the assumptions to make sure we can trust this initial test.
</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="4.5-section4-5.html#cb376-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb376-2"><a href="4.5-section4-5.html#cb376-2" tabindex="-1"></a>debt1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prodebt <span class="sc">~</span> incomegp <span class="sc">*</span> cigbuy, <span class="at">data =</span> debtRc)</span>
<span id="cb376-3"><a href="4.5-section4-5.html#cb376-3" tabindex="-1"></a><span class="fu">Anova</span>(debt1)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prodebt
##                  Sum Sq  Df F value    Pr(&gt;F)
## incomegp         10.742   4  5.5246 0.0002482
## cigbuy            0.010   1  0.0201 0.8874246
## incomegp:cigbuy   1.333   4  0.6857 0.6022065
## Residuals       183.746 378</code></pre>

<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="4.5-section4-5.html#cb378-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb378-2"><a href="4.5-section4-5.html#cb378-2" tabindex="-1"></a><span class="fu">plot</span>(debt1, <span class="at">pch =</span> <span class="dv">16</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-16"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-16-1.png" alt="Diagnostic plot for prodebt by income group and buy cigarettes/not interaction model." width="75%" />
<p class="caption">
Figure 4.16: Diagnostic plot for <code>prodebt</code> by income group and buy cigarettes/not interaction model.
</p>
</div>
<p>The diagnostic plots (Figure <a href="4.5-section4-5.html#fig:Figure4-16">4.16</a>) seem to be pretty
well-behaved with no apparent
violations of the normality assumption and no clear evidence of a violation of
the constant variance assumption. There is no indication of a problem with the independence
assumption because there is no indication of structure to the measurements of the survey
respondents that might create dependencies. In observational studies, violations
of the independence assumption might come from repeated measures of the same
person over time or multiple measurements within the same family/household or samples
that are clustered geographically, none of which are part of the survey information we have.
The random sampling from a population should
allow inferences to a larger population except for that issue of removing
partially missing responses so we can’t safely generalize results beyond the complete observations we are using without worry that the missing subjects are systematically different from those we are able to analyze.
We also don’t have much information on the exact
population sampled, so will just leave this vague here but know that there would be a
population these conclusions apply since it was random sample (at least those that would answer the questions). All of this
suggests proceeding to fitting and exploring the additive model is reasonable
here. No causal inferences are possible because this is an observational study.</p>
<ol start="0" style="list-style-type: decimal">
<li><p>After ruling out the interaction of income and cigarette status on opinions about debt, we can focus on the additive model.</p></li>
<li><p><strong>Hypotheses (Two sets apply when the additive model is the focus!):</strong></p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: No difference in means for <code>prodebt</code> for income groups in
population, given cigarette buying in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> All <span class="math inline">\(\tau_j\text{&#39;s} = 0\)</span> in additive model.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: Some difference in means for <code>prodebt</code> for income group in
population, given cigarette buying in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> Not all <span class="math inline">\(\tau_j\text{&#39;s} = 0\)</span> in additive model.</p></li>
<li><p><span class="math inline">\(H_0\)</span>: No difference in means for <code>prodebt</code> for cigarette
buying/not in population, given income group in model </span></p>
<p><span class="math inline">\(\Leftrightarrow\)</span> All <span class="math inline">\(\gamma_k\text{&#39;s} = 0\)</span> in additive model.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: Some difference in means for <code>prodebt</code> for cigarette
buying/not in population, given income group in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> Not all <span class="math inline">\(\gamma_k\text{&#39;s} = 0\)</span> in additive model.</p></li>
</ul></li>
<li><p><strong>Validity conditions – discussed above but with new plots for the additive model:</strong>
</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="4.5-section4-5.html#cb379-1" tabindex="-1"></a>debt1r <span class="ot">&lt;-</span> <span class="fu">lm</span>(prodebt <span class="sc">~</span> incomegp <span class="sc">+</span> cigbuy, <span class="at">data =</span> debtRc)</span>
<span id="cb379-2"><a href="4.5-section4-5.html#cb379-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb379-3"><a href="4.5-section4-5.html#cb379-3" tabindex="-1"></a><span class="fu">plot</span>(debt1r, <span class="at">pch =</span> <span class="dv">16</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-17"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-17-1.png" alt="Diagnostic plot of additive model for ``prodebt`` by income group and whether they buy cigarettes/not." width="75%" />
<p class="caption">
Figure 4.17: Diagnostic plot of additive model for <code>prodebt</code> by income group and whether they buy cigarettes/not.
</p>
</div>
<ul>
<li><p>Constant Variance:</p>
<ul>
<li><p>In the Residuals vs Fitted and the Scale-Location plots in
Figure <a href="4.5-section4-5.html#fig:Figure4-17">4.17</a>, the differences in variability among
groups is minor and nothing suggests a violation. <strong>If you change
models, you should always revisit the diagnostic plots to make sure you
didn’t create problems that were not present in more complicated models.</strong>
</p></li>
<li><p>We can also explore the partial residuals here as provided in
Figure <a href="4.5-section4-5.html#fig:Figure4-18">4.18</a>. The variability in the partial residuals
appears to be similar across the different levels of each predictor,
controlled for the other variable, and so does suggest any issues that
were missed by just looking at the overall residuals versus fitted
values in our regular diagnostic plots. Note how hard it is to see
differences in the mean for levels of <code>cigbuy</code> in this plot relative
to the variability in the partial residuals but that the differences in
the means in <code>incomegp</code> are at least somewhat obvious.</p></li>
</ul>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="4.5-section4-5.html#cb380-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(debt1r, <span class="at">residuals =</span> T))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-18"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-18-1.png" alt="Term-plot for additive model for ``prodebt`` by income group and whether they buy cigarettes/not with partial residuals." width="75%" />
<p class="caption">
Figure 4.18: Term-plot for additive model for <code>prodebt</code> by income group and whether they buy cigarettes/not with partial residuals.
</p>
</div></li>
<li><p>Normality of residuals:</p>
<ul>
<li>The QQ-Plot in Figure <a href="4.5-section4-5.html#fig:Figure4-17">4.17</a> does not suggest
a problem with this assumption. </li>
</ul></li>
</ul>
<p><!-- \newpage --></p></li>
<li><p><strong>Calculate the test statistics and p-values for the two main effect tests.</strong></p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="4.5-section4-5.html#cb381-1" tabindex="-1"></a><span class="fu">Anova</span>(debt1r)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prodebt
##            Sum Sq  Df F value    Pr(&gt;F)
## incomegp   10.742   4  5.5428 0.0002399
## cigbuy      0.010   1  0.0201 0.8872394
## Residuals 185.079 382</code></pre>
<ul>
<li>The test statistics are <span class="math inline">\(F(4,382) = 5.54\)</span> and <span class="math inline">\(F(1,382) = 0.0201\)</span> with p-values of 0.00024 and 0.887.</li>
</ul></li>
<li><p><strong>Conclusions (including for the initial work with the interaction test):</strong></p>
<ul>
<li>There was initially little to no evidence against the null hypothesis of no interaction
between income group and cigarette buying on pro-debt feelings
(<span class="math inline">\(F(4,378) = 0.686\)</span>, p-value = <span class="math inline">\(0.6022\)</span>) so we would conclude that there is likely
not an interaction in the population and the interaction was dropped
from the model. There is strong evidence against the null hypothesis of no
difference in the mean pro-debt feelings in the population across the income groups, after
adjusting for cigarette buying (<span class="math inline">\(F(4,382) = 5.54\)</span>, p-value = <span class="math inline">\(0.00024\)</span>), so we
would conclude that there is some difference in them. There is little evidence
against the null hypothesis of no difference in the mean pro-debt feelings in
the population based on cigarette buying/not, after adjusting for income
group (<span class="math inline">\(F(1,382) = 0.0201\)</span>, p-value = <span class="math inline">\(0.887\)</span>), so we would conclude that there
is probably not a difference across cigarette buying/not and could consider
dropping this term from the model.</li>
</ul></li>
</ol>
<p>So we learned that the additive model
was more appropriate for these responses and that the results resemble Scenario
2 or 3 with only one main effect being important. In the additive model, the
coefficients can be interpreted as shifts from the baseline after controlling
for the other variable in the model.</p>
<!-- \newpage -->
<ol start="5" style="list-style-type: decimal">
<li><p><strong>Size:</strong></p>
<ul>
<li>Figure <a href="4.5-section4-5.html#fig:Figure4-19">4.19</a> shows the increasing average comfort with being in
debt as the income groups go up except between groups 1 and 2 where 1 is a little
higher than two. Being a cigarette buyer was related to a lower comfort level
with debt but is really no different from those that did not report buying
cigarettes. It would be possible to consider follow-up tests akin to the Tukey’s
HSD comparisons for the levels of <code>incomegp</code> here but that is a bit beyond the
scope of this course – focus on the estimated mean for the 5<sup>th</sup> income group
being over 3.5 and none of the others over 3.2. That seems like an interesting
although modest difference in mean responses across income groups after
controlling for cigarette purchasing or not.</li>
</ul>

<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="4.5-section4-5.html#cb383-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(debt1r))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-19"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-19-1.png" alt="Term-plots for the prodebt response additive model with left panel for income group and the right panel for buying cigarettes or not (0 for no, 1 for yes)." width="75%" />
<p class="caption">
Figure 4.19: Term-plots for the <code>prodebt</code> response additive model with left panel for income group and the right panel for buying cigarettes or not (0 for no, 1 for yes).
</p>
</div></li>
<li><p><strong>Scope of inference:</strong></p>
<ul>
<li>Because the income group and cigarette purchasing were not (and really
could not) be randomly assigned, causal inference is not possible here. The
data set came from a random sample but from an unspecified population and
then there were missing observations. At best we can make inferences to
those in that population that would answer these questions and it would be
nice to know more about the population to really understand who this
actually applies to. There would certainly be concerns about non-response
bias in doing inference to the entire population that these data were
sampled from.</li>
</ul></li>
</ol>
<!-- \newpage -->
<p>The estimated coefficients can also be interesting to interpret for the
additive model. Here are the model summary coefficients:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="4.5-section4-5.html#cb384-1" tabindex="-1"></a><span class="fu">summary</span>(debt1r)<span class="sc">$</span>coefficients</span></code></pre></div>
<!-- \newpage -->
<pre><code>##                Estimate Std. Error    t value      Pr(&gt;|t|)
## (Intercept)  3.13127172 0.09027437 34.6861672 4.283917e-120
## incomegp2   -0.05371924 0.10860898 -0.4946114  6.211588e-01
## incomegp3    0.02680595 0.11624894  0.2305909  8.177561e-01
## incomegp4    0.09072124 0.12059542  0.7522777  4.523474e-01
## incomegp5    0.40760033 0.11392712  3.5777288  3.911633e-04
## cigbuy1     -0.01088742 0.07672982 -0.1418929  8.872394e-01</code></pre>
<p>In the model, the baseline group is for non-cigarette buyers (<code>cigbuy = 0</code>)
and income group 1 with <span class="math inline">\(\widehat{\alpha} = 3.131\)</span> points. Regardless of the
<code>cigbuy</code> level, the difference between income groups 2 and 1 is estimated
to be <span class="math inline">\(\widehat{\tau}_2 = -0.054\)</span>, an decrease in the mean score of 0.054 points.
The difference between income groups 3 and 1 is <span class="math inline">\(\widehat{\tau}_3 = 0.027\)</span>
points, regardless of cigarette smoking status. The estimated difference
between cigarette buyers and non-buyers was estimated as
<span class="math inline">\(\widehat{\gamma}_2 = -0.011\)</span> points for any income group, remember that this
variable had a large p-value in this model. The additive model-based estimates for all
six combinations can be found in Table <a href="4.5-section4-5.html#tab:Table4-3">4.3</a>.</p>
<!-- \newpage -->

<table>
<caption><span id="tab:Table4-3">Table 4.3: </span> Calculations to construct the estimates for all combinations of variables for the <code>prodebt</code> additive model.</caption>
<colgroup>
<col width="11%" />
<col width="13%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(\color{red}{\text{Cig}}\)</span><br />
<span class="math inline">\(\color{red}{\text{Buy}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group
1}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group
2}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group
3}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group
4}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group
5}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\color{red}{\text{0:No}}\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha} ={3.131}\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha} +
\widehat{\tau}_2\)</span><br />
<span class="math inline">\(=3.131 - 0.016\)</span><br />
<span class="math inline">\(= 3.115\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha} +
\widehat{\tau}_3\)</span><br />
<span class="math inline">\(=3.131 + 0.027\)</span><br />
<span class="math inline">\(= 3.158\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha} +
\widehat{\tau}_4\)</span><br />
<span class="math inline">\(=3.131 + 0.091\)</span><br />
<span class="math inline">\(= 3.222\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha} +
\widehat{\tau}_5\)</span><br />
<span class="math inline">\(=3.131 + 0.408\)</span><br />
<span class="math inline">\(= 3.539\)</span><br />
</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\color{red}{\text{1:}\text{Yes}}\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha}+\widehat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.131\)</span><br />
<span class="math inline">\(-0.011\)</span><br />
<span class="math inline">\(=3.142\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha}+\widehat{\tau}_2+\widehat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.131 - 0.016\)</span><br />
<span class="math inline">\(- 0.011\)</span><br />
<span class="math inline">\(=3.104\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha}+\widehat{\tau}_3+\widehat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.131 + 0.027\)</span><br />
<span class="math inline">\(- 0.011\)</span><br />
<span class="math inline">\(=3.147\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha}+\widehat{\tau}_4+\widehat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.131 + 0.091\)</span><br />
<span class="math inline">\(- 0.011\)</span><br />
<span class="math inline">\(=3.211\)</span></td>
<td align="left"><span class="math inline">\(\widehat{\alpha}+\widehat{\tau}_5+\widehat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.131 + 0.408\)</span><br />
<span class="math inline">\(- 0.011\)</span><br />
<span class="math inline">\(=3.528\)</span></td>
</tr>
</tbody>
</table>
<p>One final plot of the fitted values
from this additive model in Figure <a href="4.5-section4-5.html#fig:Figure4-20">4.20</a> hopefully crystallizes
the implications
of an additive model and reinforces that this model creates and assumes that
the differences across levels of one variable are the same regardless of the
level of the other variable and that this creates parallel lines. The
difference between <code>cigbuy</code> levels across all income groups is a drop in
-0.011 points. The income groups
have the same differences regardless of cigarette buying or not, with income
group 5 much higher than the other four groups. The minor differences in cigarette purchasing and large p-value for it controlled for income group suggest that we could also refine the model further and drop the <code>cigbuy</code> additive term and just focus on the income groups as a predictor – and this takes us right back to a One-Way ANOVA model so is not repeated here.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure4-20"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-20-1.png" alt="Illustration of the results from Table 4.3 showing the combined impacts of the components of the additive model for prodebt. Panel (a) uses income groups on the x-axis and different lines for cigarette buyers (1) or not (0). Panel (b) displays the different income groups as lines with the cigarette buying status on the x-axis." width="75%" />
<p class="caption">
Figure 4.20: Illustration of the results from Table <a href="4.5-section4-5.html#tab:Table4-3">4.3</a> showing the combined impacts of the components of the additive model for <code>prodebt</code>. Panel (a) uses income groups on the x-axis and different lines for cigarette buyers (1) or not (0). Panel (b) displays the different income groups as lines with the cigarette buying status on the x-axis.
</p>
</div>
<!-- \newpage -->
<p><strong>In general, we proceed through the following steps in any 2-WAY ANOVA situation:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Make a pirate-plot and an interaction plot.</p></li>
<li><p>Fit the interaction model; examine the test for the interaction.</p></li>
<li><p>Check the residual diagnostic plots for the interaction model (especially
normality and equal variance).</p>
<ul>
<li>If there is a problem with normality or
equal variance, consider a “transformation” of the response as discussed in
Chapter <a href="7-chapter7.html#chapter7">7</a>. This can help make the responses have similar
variances or responses (and the model residuals) to be more normal, but
sometimes not both. </li>
</ul></li>
<li><p>If the interaction test has a small p-value, that is your main result. Focus on
the term-plot and the interaction plot from (1) to fully understand the results, adding Tukey’s
HSD results to <code>intplot</code> to see which means of the combinations of levels are detected as
being different. Discuss the sizes of differences and the pattern of the estimated interaction.</p></li>
<li><p>If the interaction is not considered important, then re-fit the model without
the interaction (additive model) and re-check the diagnostic plots. If the
diagnostics are reasonable to proceed:</p>
<ul>
<li><p>Focus on the results for each explanatory
variable, using Type II tests especially if the design is not balanced.
Possibly consider further model refinement to only retain one of the two
variables (the one with the smaller p-value) if a p-value is large. Follow
One-Way ANOVA recommendations from this point on.</p></li>
<li><p>Report the initial interaction test
results and the results for the test for each variable from the model
that is re-fit without the interaction.</p></li>
<li><p>Model coefficients in the additive model are interesting as they are shifts from baseline
for each level of each variable, controlling for the other variable –
interpret those differences if the number of levels is not
too great.</p></li>
</ul></li>
</ol>
<p>Whether you end up favoring an additive or interaction model or do further model refinement, all steps of the
hypothesis testing protocol should be engaged and a story based on the final results should be compiled, supported by the graphical displays such as the term-plots and interaction plots.</p>
<!-- \sectionmark{Pushing Two-Way ANOVA to the limit} -->
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-R-faraway" class="csl-entry">
Faraway, Julian. 2022. <em>Faraway: Functions and Datasets for Books by Julian Faraway</em>. <a href="https://github.com/julianfaraway/faraway">https://github.com/julianfaraway/faraway</a>.
</div>
<div id="ref-Hurlbert1984" class="csl-entry">
Hurlbert, Stuart H. 1984. <span>“Pseudoreplication and the Design of Ecological Field Experiments.”</span> <em>Ecological Monographs</em> 54 (2): 187–211. <a href="http://www.jstor.org/stable/1942661">http://www.jstor.org/stable/1942661</a>.
</div>
<div id="ref-Lea1995" class="csl-entry">
Lea, Stephen E. G., Paul Webley, and Catherine M. Walker. 1995. <span>“Psychological Factors in Consumer Debt: Money Management, Economic Socialization, and Credit Use.”</span> <em>Journal of Economic Psychology</em> 16 (4): 681–701.
</div>
<div id="ref-Likert1932" class="csl-entry">
Likert, Rensis. 1932. <span>“A Technique for the Measurement of Attitudes.”</span> <em>Archives of Psychology</em> 140: 1–55.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="92">
<li id="fn92"><p>We can also use select to only retain these three variables and then <code>drop_na()</code> to get the same result for these three variables.<a href="4.5-section4-5.html#fnref92" class="footnote-back">↩︎</a></p></li>
<li id="fn93"><p>Correctly accounting for these missing data is a complex topic and you should not always engage <code>drop_na()</code>, but the first step to handling missing data issues is to find out (1) if you have an issue, (2) how prevalent it is, and (3) whether it is systematic in any way – in other words (and to date myself), “knowing is half the battle” with missing data. Consult a statistician or take more advanced statistics courses to explore this challenging topic further.<a href="4.5-section4-5.html#fnref93" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="4.4-section4-4.html"><button class="btn btn-default">Previous</button></a>
<a href="4.6-section4-6.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
