<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="5.5 Permutation tests for the \(X^2\) statistic | Intermediate Statistics with R" />
<meta property="og:type" content="book" />


<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="5.5 Permutation tests for the \(X^2\) statistic | Intermediate Statistics with R">

<title>5.5 Permutation tests for the \(X^2\) statistic | Intermediate Statistics with R</title>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if bootstrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover" id="toc-cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments" id="toc-acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1" id="toc-chapter1"><span class="toc-section-number">1</span> Preface</a>
<ul>
<li><a href="1.1-section1-1.html#section1-1" id="toc-section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1.2-section1-2.html#section1-2" id="toc-section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1.3-section1-3.html#section1-3" id="toc-section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1.4-section1-4.html#section1-4" id="toc-section1-4"><span class="toc-section-number">1.4</span> Quarto</a></li>
<li><a href="1.5-section1-5.html#section1-5" id="toc-section1-5"><span class="toc-section-number">1.5</span> Grammar of Graphics</a></li>
<li><a href="1.6-section1-6.html#section1-6" id="toc-section1-6"><span class="toc-section-number">1.6</span> Exiting RStudio</a></li>
<li><a href="1.7-section1-7.html#section1-7" id="toc-section1-7"><span class="toc-section-number">1.7</span> Chapter summary</a></li>
<li><a href="1.8-section1-8.html#section1-8" id="toc-section1-8"><span class="toc-section-number">1.8</span> Summary of important R code</a></li>
<li><a href="1.9-section1-9.html#section1-9" id="toc-section1-9"><span class="toc-section-number">1.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2" id="toc-chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a>
<ul>
<li><a href="2.1-section2-1.html#section2-1" id="toc-section2-1"><span class="toc-section-number">2.1</span> Data wrangling and density curves</a></li>
<li><a href="2.2-section2-2.html#section2-2" id="toc-section2-2"><span class="toc-section-number">2.2</span> Pirate-plots</a></li>
<li><a href="2.3-section2-3.html#section2-3" id="toc-section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2.4-section2-4.html#section2-4" id="toc-section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2.5-section2-5.html#section2-5" id="toc-section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2.6-section2-6.html#section2-6" id="toc-section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2.7-section2-7.html#section2-7" id="toc-section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2.8-section2-8.html#section2-8" id="toc-section2-8"><span class="toc-section-number">2.8</span> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</a></li>
<li><a href="2.9-section2-9.html#section2-9" id="toc-section2-9"><span class="toc-section-number">2.9</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2.10-section2-10.html#section2-10" id="toc-section2-10"><span class="toc-section-number">2.10</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2.11-section2-11.html#section2-11" id="toc-section2-11"><span class="toc-section-number">2.11</span> Chapter summary</a></li>
<li><a href="2.12-section2-12.html#section2-12" id="toc-section2-12"><span class="toc-section-number">2.12</span> Summary of important R code</a></li>
<li><a href="2.13-section2-13.html#section2-13" id="toc-section2-13"><span class="toc-section-number">2.13</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3" id="toc-chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a>
<ul>
<li><a href="3.1-section3-1.html#section3-1" id="toc-section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3.2-section3-2.html#section3-2" id="toc-section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell means and reference-coding)</a></li>
<li><a href="3.3-section3-3.html#section3-3" id="toc-section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3.4-section3-4.html#section3-4" id="toc-section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3.5-section3-5.html#section3-5" id="toc-section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3.6-section3-6.html#section3-6" id="toc-section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3.7-section3-7.html#section3-7" id="toc-section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for the Overtake data</a></li>
<li><a href="3.8-section3-8.html#section3-8" id="toc-section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3.9-section3-9.html#section3-9" id="toc-section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3.10-section3-10.html#section3-10" id="toc-section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4" id="toc-chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a>
<ul>
<li><a href="4.1-section4-1.html#section4-1" id="toc-section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4.2-section4-2.html#section4-2" id="toc-section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4.3-section4-3.html#section4-3" id="toc-section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4.4-section4-4.html#section4-4" id="toc-section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4.5-section4-5.html#section4-5" id="toc-section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4.6-section4-6.html#section4-6" id="toc-section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs and Estimability</a></li>
<li><a href="4.7-section4-7.html#section4-7" id="toc-section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4.8-section4-8.html#section4-8" id="toc-section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4.9-section4-9.html#section4-9" id="toc-section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5" id="toc-chapter5"><span class="toc-section-number">5</span> Chi-square tests</a>
<ul>
<li><a href="5.1-section5-1.html#section5-1" id="toc-section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and tableplots</a></li>
<li><a href="5.2-section5-2.html#section5-2" id="toc-section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5.3-section5-3.html#section5-3" id="toc-section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5.4-section5-4.html#section5-4" id="toc-section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5.5-section5-5.html#section5-5" id="toc-section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.6-section5-6.html#section5-6" id="toc-section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5.7-section5-7.html#section5-7" id="toc-section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5.8-section5-8.html#section5-8" id="toc-section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5.9-section5-9.html#section5-9" id="toc-section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5.10-section5-10.html#section5-10" id="toc-section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5.11-section5-11.html#section5-11" id="toc-section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5.12-section5-12.html#section5-12" id="toc-section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5.13-section5-13.html#section5-13" id="toc-section5-13"><span class="toc-section-number">5.13</span> Summary of important R code</a></li>
<li><a href="5.14-section5-14.html#section5-14" id="toc-section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6" id="toc-chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a>
<ul>
<li><a href="6.1-section6-1.html#section6-1" id="toc-section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6.2-section6-6.html#section6-6" id="toc-section6-6"><span class="toc-section-number">6.2</span> Describing relationships with a regression model</a></li>
<li><a href="6.3-section6-7.html#section6-7" id="toc-section6-7"><span class="toc-section-number">6.3</span> Least Squares Estimation</a></li>
<li><a href="6.4-section6-8.html#section6-8" id="toc-section6-8"><span class="toc-section-number">6.4</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6.5-section6-9.html#section6-9" id="toc-section6-9"><span class="toc-section-number">6.5</span> Outliers: leverage and influence</a></li>
<li><a href="6.6-section6-10.html#section6-10" id="toc-section6-10"><span class="toc-section-number">6.6</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6.7-section6-11.html#section6-11" id="toc-section6-11"><span class="toc-section-number">6.7</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6.8-section6-12.html#section6-12" id="toc-section6-12"><span class="toc-section-number">6.8</span> Chapter summary</a></li>
<li><a href="6.9-section6-13.html#section6-13" id="toc-section6-13"><span class="toc-section-number">6.9</span> Summary of important R code</a></li>
<li><a href="6.10-section6-14.html#section6-14" id="toc-section6-14"><span class="toc-section-number">6.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7" id="toc-chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a>
<ul>
<li><a href="7.1-section7-1.html#section7-1" id="toc-section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7.2-section7-2.html#section7-2" id="toc-section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7.3-section7-3.html#section7-3" id="toc-section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7.4-section7-5.html#section7-5" id="toc-section7-5"><span class="toc-section-number">7.4</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7.5-section7-6.html#section7-6" id="toc-section7-6"><span class="toc-section-number">7.5</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7.6-section7-7.html#section7-7" id="toc-section7-7"><span class="toc-section-number">7.6</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7.7-section7-8.html#section7-8" id="toc-section7-8"><span class="toc-section-number">7.7</span> Chapter summary</a></li>
<li><a href="7.8-section7-9.html#section7-9" id="toc-section7-9"><span class="toc-section-number">7.8</span> Summary of important R code</a></li>
<li><a href="7.9-section7-10.html#section7-10" id="toc-section7-10"><span class="toc-section-number">7.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8" id="toc-chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a>
<ul>
<li><a href="8.1-section8-1.html#section8-1" id="toc-section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8.2-section8-2.html#section8-2" id="toc-section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8.3-section8-3.html#section8-3" id="toc-section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8.4-section8-4.html#section8-4" id="toc-section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8.5-section8-5.html#section8-5" id="toc-section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8.6-section8-6.html#section8-6" id="toc-section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8.7-section8-7.html#section8-7" id="toc-section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8.8-section8-8.html#section8-8" id="toc-section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8.9-section8-9.html#section8-9" id="toc-section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8.10-section8-10.html#section8-10" id="toc-section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8.11-section8-11.html#section8-11" id="toc-section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8.12-section8-12.html#section8-12" id="toc-section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8.13-section8-13.html#section8-13" id="toc-section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8.14-section8-14.html#section8-14" id="toc-section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8.15-section8-15.html#section8-15" id="toc-section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8.16-section8-16.html#section8-16" id="toc-section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8.17-section8-17.html#section8-17" id="toc-section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9" id="toc-chapter9"><span class="toc-section-number">9</span> Case studies</a>
<ul>
<li><a href="9.1-section9-1.html#section9-1" id="toc-section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9.2-section9-2.html#section9-2" id="toc-section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9.3-section9-3.html#section9-3" id="toc-section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9.4-section9-4.html#section9-4" id="toc-section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9.5-section9-5.html#section9-5" id="toc-section9-5"><span class="toc-section-number">9.5</span> What do didgeridoos really do about sleepiness?</a></li>
<li><a href="9.6-section9-6.html#section9-6" id="toc-section9-6"><span class="toc-section-number">9.6</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references" id="toc-references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section5-5" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</h2>
<p>In order to assess the evidence against our null hypotheses of
no difference in distributions or no
relationship between the variables, we need to define a test
statistic and find
its distribution under the null hypothesis. The test statistic
used with both
types of tests is called the <span class="math inline">\(\mathbf{X^2}\)</span> <strong><em>statistic</em></strong>
(we want to call the statistic X-square not Chi-square). The statistic
compares the
observed counts in the contingency table to the <strong><em>expected counts</em></strong>
under the null hypothesis, with large differences between what
we observed and what we
expect under the null leading to evidence against the null hypothesis. To help
this statistic to follow a named parametric distribution and provide some
insights into sources of interesting differences from the null hypothesis, we <strong><em>standardize</em></strong><a href="#fn102" class="footnote-ref" id="fnref102"><sup>102</sup></a>
the difference between the observed and expected counts by the square-root of
the expected count.
The <span class="math inline">\(\mathbf{X^2}\)</span> <strong><em>statistic</em></strong> is based on
the sum of squared standardized differences,</p>
<p><span class="math display">\[\boldsymbol{X^2 = \Sigma^{RC}_{i = 1}\left(\frac{Observed_i-Expected_i}
{\sqrt{Expected_i}}\right)^2},\]</span></p>
<p>which is the sum over all (<span class="math inline">\(R\)</span> times <span class="math inline">\(C\)</span>) cells in the contingency
table of the square of the difference between observed and expected
cell counts divided by the square root of the
expected cell count. To calculate this test statistic, it useful to start with
a table of expected cell counts to go with our contingency table of observed
counts. The expected cell counts are easiest to understand in the
homogeneity situation but are calculated the same in either scenario.</p>
<p>The idea underlying finding the <strong><em>expected cell counts</em></strong> is to find
how many observations we would expect in category <span class="math inline">\(c\)</span> given the sample
size in that group, <span class="math inline">\(\mathbf{n_{r\bullet}}\)</span>, if the null hypothesis is true.
Under the null hypothesis across all <span class="math inline">\(R\)</span> groups
the conditional probabilities in each response category must be the
same. Consider Figure <a href="5.5-section5-5.html#fig:Figure5-7">5.7</a> where, under the null
hypothesis, the probability of <em>None</em>, <em>Some</em>, and <em>Marked</em> are the same
in both treatment groups. Specifically we have <span class="math inline">\(\text{Pr}(None) = 0.5\)</span>,
<span class="math inline">\(\text{Pr}(Some) = 0.167\)</span>, and <span class="math inline">\(\text{Pr}(Marked) = 0.333\)</span>. With
<span class="math inline">\(\mathbf{n_{Placebo\bullet}} = 43\)</span> and <span class="math inline">\(\text{Pr}(None) = 0.50\)</span>, we would
expect <span class="math inline">\(43*0.50 = 21.5\)</span> subjects to be found in the <em>Placebo, None</em>
combination if the null hypothesis were true. Similarly, with
<span class="math inline">\(\text{Pr}(Some) = 0.167\)</span>, we would expect <span class="math inline">\(43*0.167 = 7.18\)</span> in the
<em>Placebo, Some</em> cell. And for the <em>Treated</em> group with
<span class="math inline">\(\mathbf{n_{Treated\bullet}} = 41\)</span>, the expected count in the <em>Marked</em>
improvement group would be <span class="math inline">\(41*0.333 = 13.65\)</span>. Those conditional
probabilities came from aggregating across the rows because, under the null,
the row (<em>Treatment</em>) should not matter. So, the conditional
probability was actually calculated as <span class="math inline">\(\mathbf{n_{\bullet c}/N}\)</span> =
total number of responses in category <span class="math inline">\(c\)</span> divided by the table total. Since each
expected cell count was a conditional probability times the number of
observations in the row, we can re-write the expected cell count formula for
row <span class="math inline">\(r\)</span> and column <span class="math inline">\(c\)</span> as:</p>
<p><span class="math display">\[\mathbf{Expected\ cell\ count_{rc} = \frac{(n_{r\bullet}*n_{\bullet c})}{N}} =
\frac{(\text{row } r \text{ total }*\text{ column } c \text{ total})}
{\text{table total}}.\]</span></p>
<p>Table <a href="5.5-section5-5.html#tab:Table5-3">5.3</a> demonstrates the calculations of the
expected cell counts using this formula for all 6 cells in the <span class="math inline">\(2\times 3\)</span>
table.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure5-7"></span>
<img src="05-chiSquaredTests_files/figure-html/Figure5-7-1.png" alt="Stacked bar chart that could occur if the null hypothesis were true for the Arthritis study." width="75%" />
<p class="caption">
Figure 5.7: Stacked bar chart that could occur if the null hypothesis were true for the Arthritis study.
</p>
</div>
<!-- \newpage -->

<table>
<caption><span id="tab:Table5-3">Table 5.3: </span> Demonstration of calculation of expected cell counts for Arthritis data.</caption>
<colgroup>
<col width="8%" />
<col width="25%" />
<col width="25%" />
<col width="26%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">    </th>
<th align="left"><strong>None</strong></th>
<th align="left"><strong>Some</strong></th>
<th align="left"><strong>Marked</strong></th>
<th align="left"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>Placebo</strong></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Placebo}\bullet}*n_{\bullet\text{None}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{43*42}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{21.5}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Placebo}\bullet}*n_{\bullet\text{Some}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{43*14}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{7.167}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Placebo}\bullet}*n_{\bullet\text{Marked}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{43*28}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{14.33}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{n_{\text{Placebo}\bullet}
=
43}\)</span></td>
</tr>
<tr class="even">
<td align="left"><strong>Treated</strong></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Treated}\bullet}*n_{\bullet\text{None}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{41*42}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{20.5}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Treated}\bullet}*n_{\bullet\text{Some}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{41*14}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{6.83}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{\dfrac{n_{\text{Treated}\bullet}*n_{\bullet\text{Marked}}}{N}}\)</span>
<span class="math inline">\(\boldsymbol{
=
\dfrac{41*28}{84}}\)</span>
<span class="math inline">\(\boldsymbol{ =
\color{red}{\mathbf{13.67}}}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{n_{\text{Treated}\bullet}
=
41}\)</span></td>
</tr>
<tr class="odd">
<td align="left"><strong>Totals</strong></td>
<td align="left"><span class="math inline">\(\boldsymbol{n_{\bullet\text{None}}
=
42}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{n_{\bullet\text{Some}}
=
14}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{n_{\bullet\text{Marked}}
=
28}\)</span></td>
<td align="left"><span class="math inline">\(\boldsymbol{N = 84}\)</span></td>
</tr>
</tbody>
</table>
<p>Of course, using R can help us avoid tedium like this… The main
engine for results in this chapter is the <code>chisq.test</code>
function. It operates on a table of
counts that has been produced <strong>without row or column totals</strong>.</p>
<!-- \newpage -->
<p>For example, <code>Arthtable</code> below contains just the observed cell
counts. Applying the <code>chisq.test</code> function<a href="#fn103" class="footnote-ref" id="fnref103"><sup>103</sup></a> to <code>Arthtable</code>
provides a variety of useful output. For the moment, we are just
going to extract the information in the “<code>expected</code>” attribute of
the results from running this function (using <code>chisq.test(TABLENAME)$expected)</code>.
These are the expected cell counts which match the previous calculations
except for some rounding in the hand-calculations.</p>
<!-- \newpage -->
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="5.5-section5-5.html#cb416-1" tabindex="-1"></a>Arthtable <span class="ot">&lt;-</span> <span class="fu">tally</span>(<span class="sc">~</span> Treatment <span class="sc">+</span> Improved, <span class="at">data =</span> Arthritis)</span>
<span id="cb416-2"><a href="5.5-section5-5.html#cb416-2" tabindex="-1"></a>Arthtable</span></code></pre></div>
<pre><code>##          Improved
## Treatment None Some Marked
##   Placebo   29    7      7
##   Treated   13    7     21</code></pre>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="5.5-section5-5.html#cb418-1" tabindex="-1"></a><span class="fu">chisq.test</span>(Arthtable)<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##          Improved
## Treatment None     Some   Marked
##   Placebo 21.5 7.166667 14.33333
##   Treated 20.5 6.833333 13.66667</code></pre>
<p>With the observed and expected cell counts in hand, we can turn our
attention to calculating the test
statistic. It is possible to lay out the “contributions” to the
<span class="math inline">\(X^2\)</span> statistic in a table format, allowing a simple way to finally
calculate the statistic without losing any information. For <strong>each cell</strong>
we need to find</p>
<p><span class="math display">\[(\text{observed}-\text{expected})/\sqrt{\text{expected}},\]</span></p>
<p><strong>square them</strong>, and then we need to add them <strong>all</strong> up. In the
current example, there are 6 cells to add up (<span class="math inline">\(R = 2\)</span> times <span class="math inline">\(C = 3\)</span>), shown
in Table <a href="5.5-section5-5.html#tab:Table5-4">5.4</a>.</p>

<table>
<caption><span id="tab:Table5-4">Table 5.4: </span> <span class="math inline">\(X^2\)</span> contributions for the Arthritis data.</caption>
<colgroup>
<col width="16%" />
<col width="27%" />
<col width="27%" />
<col width="28%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">    </th>
<th align="left"><strong>None</strong></th>
<th align="left"><strong>Some</strong></th>
<th align="left"><strong>Marked</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>Placebo</strong></td>
<td align="left"><span class="math inline">\(\left(\frac{29-21.5}{\sqrt{21.5}}\right)^2
=
\color{red}{\mathbf{2.616}}\)</span></td>
<td align="left"><span class="math inline">\(\left(\frac{7-7.167}{\sqrt{7.167}}\right)^2
=
\color{red}{\mathbf{0.004}}\)</span></td>
<td align="left"><span class="math inline">\(\left(\frac{7-14.33}{\sqrt{14.33}}\right)^2
=
\color{red}{\mathbf{3.752}}\)</span></td>
</tr>
<tr class="even">
<td align="left"><strong>Treated</strong></td>
<td align="left"><span class="math inline">\(\left(\frac{13-20.5}{\sqrt{20.5}}\right)^2
=
\color{red}{\mathbf{2.744}}\)</span></td>
<td align="left"><span class="math inline">\(\left(\frac{7-6.833}{\sqrt{6.833}}\right)^2
=
\color{red}{\mathbf{0.004}}\)</span></td>
<td align="left"><span class="math inline">\(\left(\frac{21-13.67}{\sqrt{13.67}}\right)^2
=
\color{red}{\mathbf{3.935}}\)</span></td>
</tr>
</tbody>
</table>
<p>Finally, the <span class="math inline">\(X^2\)</span> statistic here is the sum of these six results
<span class="math inline">\(= {\color{red}{2.616+0.004+3.752+2.744+0.004+3.935}} = 13.055\)</span></p>
<p>Our favorite function in this chapter, <code>chisq.test</code>, does not provide
the contributions to the <span class="math inline">\(X^2\)</span> statistic directly. It provides a related
quantity called the </p>
<p><span class="math display">\[\textbf{standardized residual} = \left(\frac{\text{Observed}_i -
\text{Expected}_i}{\sqrt{\text{Expected}_i}}\right),\]</span></p>
<p>which, when squared (in R, squaring is accomplished using <code>^2</code>),
is the contribution of that particular cell to the <span class="math inline">\(X^2\)</span>
statistic that is displayed in Table <a href="5.5-section5-5.html#tab:Table5-4">5.4</a>.</p>
<!-- \newpage -->
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="5.5-section5-5.html#cb420-1" tabindex="-1"></a>(<span class="fu">chisq.test</span>(Arthtable)<span class="sc">$</span>residuals)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##          Improved
## Treatment        None        Some      Marked
##   Placebo 2.616279070 0.003875969 3.751937984
##   Treated 2.743902439 0.004065041 3.934959350</code></pre>
<p>The most common error made in calculating the <span class="math inline">\(X^2\)</span> statistic by hand
involves having observed less than expected
and then failing to make the <span class="math inline">\(X^2\)</span> contribution positive for all cells
(remember you are <strong>squaring the entire quantity</strong> in the parentheses
and so the sign has to go positive!). In R, we can add up the cells using
the <code>sum</code> function over the entire table of numbers:</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="5.5-section5-5.html#cb422-1" tabindex="-1"></a><span class="fu">sum</span>((<span class="fu">chisq.test</span>(Arthtable)<span class="sc">$</span>residuals)<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 13.05502</code></pre>
<p>Or we can let R do all this hard work for us and get straight to the
good stuff:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="5.5-section5-5.html#cb424-1" tabindex="-1"></a><span class="fu">chisq.test</span>(Arthtable)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  Arthtable
## X-squared = 13.055, df = 2, p-value = 0.001463</code></pre>
<p>The <code>chisq.test</code> function reports a p-value by
default. Before we discover how it got that result, we can rely on our
permutation methods to obtain a distribution for the <span class="math inline">\(X^2\)</span> statistic
under the null hypothesis. As in Chapters <a href="2-chapter2.html#chapter2">2</a> and <a href="3-chapter3.html#chapter3">3</a>,
this will allow us to find a
p-value while relaxing one of our assumptions<a href="#fn104" class="footnote-ref" id="fnref104"><sup>104</sup></a>.
In the One-WAY ANOVA in Chapter <a href="3-chapter3.html#chapter3">3</a>, we permuted the
grouping variable relative
to the responses, mimicking the null hypothesis that the groups are the same
and so we can shuffle them around if the null is true. That same technique is
useful here. If we randomly permute the grouping variable used to form the rows
in the contingency table relative to the responses in the other variable and
track the possibilities available for the <span class="math inline">\(X^2\)</span> statistic under
permutations, we can find the probability of getting a result as extreme as or
more extreme than what we observed assuming the null is true, our p-value.
The observed statistic is the
<span class="math inline">\(X^2\)</span> calculated using the formula above.
Like the <span class="math inline">\(F\)</span>-statistic, it ends up
that only results in the right tail of this distribution are desirable for
finding evidence against the null hypothesis
because all the values showing deviation from the null in any direction going into the statistic have to be positive. You can see this by observing that
values of the <span class="math inline">\(X^2\)</span> statistic close to 0 are generated when the
observed values are close to the expected values and that sort of result should
not be used to find evidence against the null. When the observed and expected
values are “far apart”, then we should find evidence against the null. It is
helpful to work through some examples to be able to understand how the <span class="math inline">\(X^2\)</span>
statistic “measures” differences between observed and expected.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure5-8"></span>
<img src="05-chiSquaredTests_files/figure-html/Figure5-8-1.png" alt="Stacked bar charts of four permuted Arthritis data sets that produced \(X^2\) between 0.62 and 2.38." width="75%" />
<p class="caption">
Figure 5.8: Stacked bar charts of four permuted Arthritis data sets that produced <span class="math inline">\(X^2\)</span> between 0.62 and 2.38.
</p>
</div>
<p>To start, compare the previous observed <span class="math inline">\(X^2\)</span> of 13.055 to the sort of
results we obtain in a single permutation of the treated/placebo labels
– Figure <a href="5.5-section5-5.html#fig:Figure5-8">5.8</a> (top left panel) shows
a permuted data set that produced <span class="math inline">\(X^{2*} = 0.62\)</span>. Visually, you can only
see minimal differences between the treatment and placebo groups showing up in
the stacked bar chart. Three other permuted data sets are displayed in
Figure <a href="5.5-section5-5.html#fig:Figure5-8">5.8</a> showing the variability in results in
permutations but that none get close
to showing the differences in the bars observed in the real data set in Figure <a href="5.1-section5-1.html#fig:Figure5-2">5.2</a>.</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="5.5-section5-5.html#cb426-1" tabindex="-1"></a>Arthperm <span class="ot">&lt;-</span> Arthritis</span>
<span id="cb426-2"><a href="5.5-section5-5.html#cb426-2" tabindex="-1"></a>Arthperm <span class="ot">&lt;-</span> Arthperm <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">PermTreatment =</span> <span class="fu">shuffle</span>(Treatment))</span></code></pre></div>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="5.5-section5-5.html#cb427-1" tabindex="-1"></a><span class="fu">plot</span>(Improved <span class="sc">~</span> PermTreatment, <span class="at">data =</span> Arthperm,</span>
<span id="cb427-2"><a href="5.5-section5-5.html#cb427-2" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Stacked Bar Chart of Permuted Arthritis Data&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="5.5-section5-5.html#cb428-1" tabindex="-1"></a>Arthpermtable <span class="ot">&lt;-</span> <span class="fu">tally</span>(<span class="sc">~</span> PermTreatment <span class="sc">+</span> Improved, <span class="at">data =</span> Arthperm)</span>
<span id="cb428-2"><a href="5.5-section5-5.html#cb428-2" tabindex="-1"></a>Arthpermtable</span></code></pre></div>
<pre><code>##              Improved
## PermTreatment None Some Marked
##       Placebo   22    6     15
##       Treated   20    8     13</code></pre>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="5.5-section5-5.html#cb430-1" tabindex="-1"></a><span class="fu">chisq.test</span>(Arthpermtable)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  Arthpermtable
## X-squared = 0.47646, df = 2, p-value = 0.788</code></pre>
<p>To build the permutation-based null distribution for the <span class="math inline">\(X^2\)</span> statistic,
we need to collect up the test statistics (<span class="math inline">\(X^{2*}\)</span>) in many of these permuted
results. The code is similar to permutation tests in Chapters
<a href="2-chapter2.html#chapter2">2</a> and <a href="3-chapter3.html#chapter3">3</a> except
that each permutation generates a new contingency table that is summarized and
provided to <code>chisq.test</code> to analyze. We extract the
<code>$statistic</code> attribute of the results from running <code>chisq.test</code>.
</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="5.5-section5-5.html#cb432-1" tabindex="-1"></a>Tobs <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(Arthtable)<span class="sc">$</span>statistic; Tobs</span></code></pre></div>
<pre><code>## X-squared 
##  13.05502</code></pre>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="5.5-section5-5.html#cb434-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb434-2"><a href="5.5-section5-5.html#cb434-2" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb434-3"><a href="5.5-section5-5.html#cb434-3" tabindex="-1"></a>Tstar <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> B)</span>
<span id="cb434-4"><a href="5.5-section5-5.html#cb434-4" tabindex="-1"></a><span class="cf">for</span> (b <span class="cf">in</span> (<span class="dv">1</span><span class="sc">:</span>B)){</span>
<span id="cb434-5"><a href="5.5-section5-5.html#cb434-5" tabindex="-1"></a>  Tstar[b] <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="fu">tally</span>(<span class="sc">~</span> <span class="fu">shuffle</span>(Treatment) <span class="sc">+</span> Improved,</span>
<span id="cb434-6"><a href="5.5-section5-5.html#cb434-6" tabindex="-1"></a>                               <span class="at">data =</span> Arthritis))<span class="sc">$</span>statistic</span>
<span id="cb434-7"><a href="5.5-section5-5.html#cb434-7" tabindex="-1"></a>}</span>
<span id="cb434-8"><a href="5.5-section5-5.html#cb434-8" tabindex="-1"></a><span class="fu">pdata</span>(Tstar, Tobs, <span class="at">lower.tail =</span> F)[[<span class="dv">1</span>]]</span></code></pre></div>
<pre><code>## [1] 0.002</code></pre>
<div style="page-break-after: always;"></div>

<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="5.5-section5-5.html#cb436-1" tabindex="-1"></a><span class="fu">tibble</span>(Tstar) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tstar)) <span class="sc">+</span> </span>
<span id="cb436-2"><a href="5.5-section5-5.html#cb436-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..ncount..), <span class="at">bins =</span> <span class="dv">20</span>, <span class="at">col =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">&quot;khaki&quot;</span>) <span class="sc">+</span> </span>
<span id="cb436-3"><a href="5.5-section5-5.html#cb436-3" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..scaled..)) <span class="sc">+</span></span>
<span id="cb436-4"><a href="5.5-section5-5.html#cb436-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb436-5"><a href="5.5-section5-5.html#cb436-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span></span>
<span id="cb436-6"><a href="5.5-section5-5.html#cb436-6" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> Tobs, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb436-7"><a href="5.5-section5-5.html#cb436-7" tabindex="-1"></a>  <span class="fu">stat_bin</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..ncount.., <span class="at">label =</span> ..count..), <span class="at">bins =</span> <span class="dv">20</span>,</span>
<span id="cb436-8"><a href="5.5-section5-5.html#cb436-8" tabindex="-1"></a>           <span class="at">geom =</span> <span class="st">&quot;text&quot;</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.75</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Figure5-9"></span>
<img src="05-chiSquaredTests_files/figure-html/Figure5-9-1.png" alt="Permutation distribution for the \(X^2\) statistic for the Arthritis data with an observed \(X^2\) of 13.1 (bold, vertical line)." width="75%" />
<p class="caption">
Figure 5.9: Permutation distribution for the <span class="math inline">\(X^2\)</span> statistic for the Arthritis data with an observed <span class="math inline">\(X^2\)</span> of 13.1 (bold, vertical line).
</p>
</div>
<p>For an observed <span class="math inline">\(X^2\)</span> statistic of 13.055, two out of 1,000 permutation
results matched or exceeded this value (<code>pdata</code> returned a value of
0.002) as displayed in Figure <a href="5.5-section5-5.html#fig:Figure5-9">5.9</a>.
This suggests that our observed result is quite extreme
relative to the null
hypothesis and provides strong evidence against it.
</p>
<!-- \newpage -->
<p><strong>Validity conditions</strong> for a permutation <span class="math inline">\(X^2\)</span> test are:
</p>
<ol style="list-style-type: decimal">
<li><p>Independence of observations.
</p></li>
<li><p>Both variables are categorical.</p></li>
<li><p>Expected cell counts &gt; 0 (otherwise <span class="math inline">\(X^2\)</span> is not defined).</p></li>
</ol>
<p>For the permutation approach described here to provide valid inferences
we need to be working with
observations that are independent of one another. One way that a violation of
independence can sometimes occur in this situation is when a single subject
shows up in the table more than once. For example, if a single individual
completes a survey more than once and those results are reported as if they
came from <span class="math inline">\(N\)</span> independent individuals.
Be careful about this as it is really easy to make tables of poorly collected
or non-independent observations and then consider them for these analyses. Poor
data still lead to poor conclusions even if you have fancy new statistical
tools to use!</p>
</div>
<div class="footnotes">
<hr />
<ol start="102">
<li id="fn102"><p>Standardizing involves dividing by the standard deviation
of a quantity so it has a standard deviation 1 regardless of its original
variability and that is what is happening here even though it doesn’t
look like the standardization you are used to with continuous variables.<a href="5.5-section5-5.html#fnref102" class="footnote-back">↩︎</a></p></li>
<li id="fn103"><p>Note that in smaller data sets to get results as discussed here, use the <code>correct = F</code> option. If you get output that contains “<code>...with Yate's continuity correction</code>”, a slightly modified version of this test is being used.<a href="5.5-section5-5.html#fnref103" class="footnote-back">↩︎</a></p></li>
<li id="fn104"><p>Here it allows us to relax
a requirement that all the expected cell counts are larger than 5 for the
parametric test (Section <a href="5.6-section5-6.html#section5-6">5.6</a>).<a href="5.5-section5-5.html#fnref104" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="5.4-section5-4.html"><button class="btn btn-default">Previous</button></a>
<a href="5.6-section5-6.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
